import { describe, expect, it } from "vitest";
import type { FinanceAccount, FinanceInvoice, FinancePayment } from "../core/types";
import { accountRecordBalance, canWriteFinance, currencyOverview, invoiceOverdue, maskIban, maskTaxId, paymentPercentage, productionFinanceCoverage, type FinanceSnapshot } from "./financeUIModel";
import { buildProductionFinanceSignals, productionSignalsOnly } from "./productionFinanceSignals";

const account=(overrides:Partial<FinanceAccount>={}):FinanceAccount=>({id:"a1",companyId:"c1",name:"Banka",accountType:"bank",currency:"TRY",iban:"TR001234567890123456789012",openingBalance:100,archivedAt:null,createdBy:"u1",updatedBy:"u1",createdAt:"2026-07-01",updatedAt:"2026-07-01",...overrides});
const invoice=(overrides:Partial<FinanceInvoice>={}):FinanceInvoice=>({id:"i1",companyId:"c1",invoiceNumber:"FTR-1",invoiceType:"sales",sourceSalesOrderId:"o1",partyId:"p1",contactId:null,opportunityId:null,ownerUserId:"u1",status:"issued",currency:"TRY",issueDate:"2026-07-01",dueDate:"2026-07-10",paymentTerms:null,customerNotes:null,internalNotes:null,partyDisplayName:"Kurgusal AŞ",partyTaxId:null,partyTaxOffice:null,partyAddress:null,contactDisplayName:null,contactEmail:null,contactPhone:null,subtotal:1000,discountTotal:0,taxTotal:200,otherTaxTotal:0,grandTotal:1200,paidAmount:200,outstandingAmount:1000,issuedAt:"2026-07-01",paidAt:null,cancelledAt:null,cancellationReason:null,archivedAt:null,createdBy:"u1",updatedBy:"u1",createdAt:"2026-07-01",updatedAt:"2026-07-01",...overrides});
const payment=(overrides:Partial<FinancePayment>={}):FinancePayment=>({id:"pay1",companyId:"c1",paymentNumber:"THS-1",direction:"inflow",partyId:"p1",accountId:"a1",paymentDate:"2026-07-05",currency:"TRY",amount:200,paymentMethod:"bank_transfer",externalReference:null,note:null,postedAt:"2026-07-05",createdBy:"u1",createdAt:"2026-07-05",...overrides});
const snapshot=(overrides:Partial<FinanceSnapshot>={}):FinanceSnapshot=>({accounts:[account()],balances:{a1:300},invoices:[invoice()],payments:[payment()],schedule:[{invoiceId:"i1",invoiceNumber:"FTR-1",partyId:"p1",partyDisplayName:"Kurgusal AŞ",dueDate:"2026-07-10",currency:"TRY",outstandingAmount:1000,overdue:true,daysOverdue:5,agingBucket:"1_30"}],...overrides});

describe("Finance UI production cutover model",()=>{
 it("keeps permissions owner/employee writable and accountant read-only",()=>{expect(canWriteFinance("owner")).toBe(true);expect(canWriteFinance("employee")).toBe(true);expect(canWriteFinance("accountant")).toBe(false)});
 it("masks IBAN and tax IDs in list contexts",()=>{expect(maskIban(account().iban)).toBe("TR00 •••• •••• 9012");expect(maskTaxId("1234567890")).toBe("12••••••90")});
 it("derives account record balance only from opening balance and recorded payments",()=>expect(accountRecordBalance(account(),[payment(),payment({id:"p2",direction:"outflow",amount:50})])).toBe(250));
 it("separates overview metrics by currency",()=>{const rows=currencyOverview(snapshot({accounts:[account(),account({id:"a2",currency:"EUR"})],invoices:[invoice(),invoice({id:"i2",currency:"EUR"})],schedule:[snapshot().schedule[0],{...snapshot().schedule[0],invoiceId:"i2",currency:"EUR",outstandingAmount:50}]}),new Date("2026-07-15"));expect(rows.map(x=>x.currency)).toEqual(["TRY","EUR"]);expect(rows[0].openReceivable).toBe(1000);expect(rows[1].openReceivable).toBe(50)});
 it("never combines currencies into one total",()=>expect(currencyOverview(snapshot(),new Date("2026-07-15"))[0].currency).toBe("TRY"));
 it("derives payment percentage and overdue state",()=>{expect(Math.round(paymentPercentage(invoice()))).toBe(17);expect(invoiceOverdue(invoice(),new Date("2026-07-15"))).toBe(true)});
 it("excludes draft, paid, cancelled and archived invoices from expected signals",()=>{const rows=[invoice({id:"draft",status:"draft"}),invoice({id:"paid",status:"paid",outstandingAmount:0}),invoice({id:"cancel",status:"cancelled"}),invoice({id:"archived",archivedAt:"2026-07-02"})];expect(buildProductionFinanceSignals(snapshot({invoices:rows,payments:[]}))).toEqual([])});
 it("emits expected collection only for open operational invoices",()=>{const signals=buildProductionFinanceSignals(snapshot({payments:[]}));expect(signals).toHaveLength(1);expect(signals[0].metadata?.expected).toBe(true);expect(signals[0].amount).toBe(1000)});
 it("labels recorded collections as historical rather than future starting cash",()=>expect(buildProductionFinanceSignals(snapshot({invoices:[]}))[0].metadata).toMatchObject({historical:true,verifiedStartingCash:false}));
 it("removes legacy finance signals before appending production signals",()=>{const legacy={...buildProductionFinanceSignals(snapshot({payments:[]}))[0],id:"legacy"};expect(productionSignalsOnly([legacy],snapshot({payments:[]})).some(x=>x.id==="legacy")).toBe(false)});
 it("reports missing coverage without Supabase data",()=>expect(productionFinanceCoverage(snapshot({accounts:[],invoices:[],payments:[],schedule:[]})).status).toBe("missing"));
 it("blocks bank balance, runway and reconciliation claims",()=>expect(productionFinanceCoverage(snapshot()).blockedCapabilities).toEqual(expect.arrayContaining(["Doğrulanmış nakit pozisyonu","Banka mutabakatı","Nakit pisti"])));
 it("does not use VKN as the canonical relationship",()=>expect(snapshot().schedule[0].partyId).toBe("p1"));
});
