/* eslint-disable react-hooks/set-state-in-effect -- linked invoice follows the selected sales order */
import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Modal from "../../../surfaces/dashboard/components/Modal";
import type { SalesOrder } from "../../sales/orders/types";
import { createSalesInvoiceFromSalesOrder, getFinanceInvoiceForSalesOrder } from "../core/financeRepository";
import type { FinanceInvoice } from "../core/types";
import { financeInvoiceStatusLabels } from "../core/financeViewModel";
import { canWriteFinance } from "./financeUIModel";
import { Info, Money, Notice, inputClass, primary, secondary } from "./FinanceUI";

export default function SalesOrderInvoicePanel({companyId,role,order,itemCount,partyName,contactName,opportunityName}:{companyId:string;role:string|null|undefined;order:SalesOrder;itemCount:number;partyName:string;contactName:string|null;opportunityName:string|null}){
 const navigate=useNavigate();const [invoice,setInvoice]=useState<FinanceInvoice|null>(null);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10));const [dueDate,setDueDate]=useState("");const [customerNote,setCustomerNote]=useState("");const [internalNote,setInternalNote]=useState("");
 const load=useCallback(async()=>{setLoading(true);const result=await getFinanceInvoiceForSalesOrder(companyId,order.id);setError(result.error?.message??"");setInvoice(result.data??null);setLoading(false)},[companyId,order.id]);useEffect(()=>{void load()},[load]);
 const convert=async()=>{if(dueDate<issueDate)return setError("Vade tarihi düzenleme tarihinden önce olamaz.");setSaving(true);const result=await createSalesInvoiceFromSalesOrder(companyId,{salesOrderId:order.id,issueDate,dueDate,customerNote,internalNote});setSaving(false);if(result.error)return setError(result.error.message);setOpen(false);await load();navigate(`/dashboard/finans/faturalar/${result.data.invoiceId}`,{state:{notice:"Fatura kaydı başarıyla oluşturuldu."}})};
 const eligible=order.status==='completed'&&!order.archivedAt&&canWriteFinance(role);
 return <section className="rounded-card border border-line bg-surface p-5"><h2 className="font-serif text-xl">Finans faturası</h2>{error&&<Notice error>{error}</Notice>}{loading?<p className="mt-3 text-sm text-ink-mute">Fatura bağlantısı kontrol ediliyor…</p>:invoice?<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line p-4"><div><strong>{invoice.invoiceNumber}</strong><p className="text-sm text-ink-soft">{financeInvoiceStatusLabels[invoice.status]} · açık <Money value={invoice.outstandingAmount} currency={invoice.currency}/></p></div><Link className={secondary} to={`/dashboard/finans/faturalar/${invoice.id}`}>Faturayı aç</Link></div>:eligible?<button type="button" className={`${primary} mt-4`} onClick={()=>setOpen(true)}>Fatura oluştur</button>:<p className="mt-3 text-sm text-ink-soft">{order.status==='completed'?"Bu sipariş için henüz fatura yok; oluşturma yetkiniz bulunmuyor.":"Fatura yalnız tamamlanmış satış siparişinden oluşturulabilir."}</p>}{open&&<Modal title="Fatura oluştur" onClose={()=>!saving&&setOpen(false)} width="700px"><p className="rounded-lg bg-warn/5 p-3 text-sm">Bu kayıt Octo içindeki alacak kaydıdır. Yasal e-Fatura veya e-Arşiv gönderimi yapılmaz.</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Satış siparişi">{order.orderNumber}</Info><Info label="Firma">{partyName}</Info><Info label="İlgili kişi">{contactName??"—"}</Info><Info label="Fırsat">{opportunityName??"—"}</Info><Info label="Toplam"><Money value={order.grandTotal} currency={order.currency}/></Info><Info label="Kalem sayısı">{itemCount}</Info><Info label="Ödeme koşulları">{order.paymentTerms??"—"}</Info><Info label="Para birimi">{order.currency}</Info></dl><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Düzenleme tarihi<input type="date" className={`${inputClass} mt-1`} value={issueDate} onChange={e=>setIssueDate(e.target.value)}/></label><label className="text-sm">Vade tarihi<input required type="date" className={`${inputClass} mt-1`} value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div><label className="mt-3 block text-sm">Müşteri notu<textarea className={`${inputClass} mt-1`} value={customerNote} onChange={e=>setCustomerNote(e.target.value)}/></label><label className="mt-3 block text-sm">İç not<textarea className={`${inputClass} mt-1`} value={internalNote} onChange={e=>setInternalNote(e.target.value)}/></label>{error&&<p role="alert" className="mt-3 text-sm text-crimson">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className={secondary} onClick={()=>setOpen(false)}>Vazgeç</button><button type="button" disabled={saving||!dueDate} className={primary} onClick={()=>void convert()}>{saving?'Oluşturuluyor…':'Fatura oluştur'}</button></div></Modal>}</section>
}
