// Octo — Posting Bridge
// Connects operational finance events to the general ledger. The finance store
// calls these after an invoice/settlement so the GL stays in lockstep with the
// operational layer — the same consistency principle as cash settlement.
//
// Kept separate from the finance store to avoid a circular import.

import type { Invoice, Transaction } from '../types'
import {
  postSalesInvoice, postPurchaseInvoice, postCollection, postPayment,
  postBankTransaction, makeEntry,
} from './posting'
import { postEntry, peekNextFisNo, removeEntriesBySource, clearLedger } from './ledgerStore'

// Post the journal entry for a newly created invoice (accrual: the obligation
// exists when the invoice is issued, regardless of payment).
export function postInvoiceCreated(inv: Invoice) {
  const lines = inv.type === 'sales' ? postSalesInvoice(inv) : postPurchaseInvoice(inv)
  const kaynak = inv.type === 'sales' ? 'satis_faturasi' : 'alis_faturasi'
  const entry = makeEntry(
    inv.issueDate || new Date().toISOString().split('T')[0],
    kaynak,
    `${inv.contactName} — ${inv.type === 'sales' ? 'Satış' : 'Alış'} faturası`,
    lines,
    peekNextFisNo(),
    inv.id,
  )
  postEntry(entry)
}

// Post the settlement (collection or payment) when an invoice is marked paid.
export function postInvoiceSettled(inv: Invoice) {
  const lines = inv.type === 'sales' ? postCollection(inv) : postPayment(inv)
  const kaynak = inv.type === 'sales' ? 'tahsilat' : 'odeme'
  const entry = makeEntry(
    new Date().toISOString().split('T')[0],
    kaynak,
    `${inv.contactName} — ${inv.type === 'sales' ? 'Tahsilat' : 'Ödeme'}`,
    lines,
    peekNextFisNo(),
    inv.id + ':settle',
  )
  postEntry(entry)
}

// Post a standalone bank transaction not generated by an invoice settlement.
export function postStandaloneTransaction(tx: Transaction) {
  if (tx.invoiceId) return // invoice-linked txns are posted via settlement
  const lines = postBankTransaction(tx)
  const entry = makeEntry(
    tx.date,
    'banka',
    tx.description,
    lines,
    peekNextFisNo(),
    'tx:' + tx.id,
  )
  postEntry(entry)
}

export { removeEntriesBySource }

// Bulk-post a full dataset to the ledger (used when seeding demo mode). Clears
// any existing ledger first so demo seeding is idempotent. Posts each invoice's
// accrual entry, a settlement entry for paid invoices, and standalone txns.
export function postDemoLedger(data: { invoices: Invoice[]; transactions: Transaction[] }) {
  clearLedger()
  // Oldest-first so fiş numbers run chronologically.
  const invoices = [...data.invoices].sort((a, b) => (a.issueDate < b.issueDate ? -1 : 1))
  for (const inv of invoices) {
    postInvoiceCreated(inv)
    if (inv.status === 'paid') postInvoiceSettled(inv)
  }
  for (const tx of data.transactions) {
    if (!tx.invoiceId) postStandaloneTransaction(tx)
  }
}
