import {describe,expect,it,vi} from 'vitest'
import migration from '../../../../supabase/migrations/20260712223000_sales_execution_data_foundation_v1.sql?raw'
import {createSalesExecutionRepository,mapSalesExecutionError,type SalesExecutionClient} from './salesExecutionRepository'
import {normalizeActivityInput,normalizeLeadInput,normalizeOpportunityInput} from './validation'
import {activityLabels,leadDisplayName,leadStatusLabels,opportunityIsOverdue,opportunityIsStale,opportunityNeedsNextAction,opportunityState,stageProbability,taskIsDueToday,taskIsOverdue,weightedOpportunityValue} from './salesExecutionViewModel'
import type {SalesActivity,SalesLead,SalesOpportunity,SalesPipelineStage} from './types'

class Q implements PromiseLike<{data:unknown;error:unknown|null}>{ops:Array<[string,...unknown[]]>=[];constructor(private response={data:[] as unknown,error:null as unknown|null}){}select(v:string){this.ops.push(['select',v]);return this}insert(v:Record<string,unknown>){this.ops.push(['insert',v]);return this}update(v:Record<string,unknown>){this.ops.push(['update',v]);return this}eq(a:string,b:unknown){this.ops.push(['eq',a,b]);return this}is(a:string,b:null){this.ops.push(['is',a,b]);return this}order(a:string,b?:{ascending?:boolean}){this.ops.push(['order',a,b]);return this}maybeSingle(){this.ops.push(['maybeSingle']);return Promise.resolve(this.response)}then<A={data:unknown;error:unknown|null},B=never>(ok?:((v:{data:unknown;error:unknown|null})=>A|PromiseLike<A>)|null,bad?:((r:unknown)=>B|PromiseLike<B>)|null){return Promise.resolve(this.response).then(ok,bad)}}
class Client{queries:Array<{table:string;q:Q}>=[];rpc=vi.fn(async()=>({data:[{party_id:'p',contact_id:'c',opportunity_id:'o'}],error:null}));constructor(private responses:Array<{data:unknown;error:unknown|null}>=[]){}from(table:string){const q=new Q(this.responses.shift());this.queries.push({table,q});return q}}
const stage=(overrides:Partial<SalesPipelineStage>={}):SalesPipelineStage=>({id:'s',companyId:'c',pipelineId:'p',name:'Yeni fırsat',stageKey:'new',position:1,defaultProbability:10,staleAfterDays:7,isClosed:false,outcome:null,requiredFields:[],recommendedActions:[],createdAt:'2026-01-01',updatedAt:'2026-01-01',...overrides})
const opportunity=(overrides:Partial<SalesOpportunity>={}):SalesOpportunity=>({id:'o',companyId:'c',partyId:'p',pipelineId:'pl',stageId:'s',ownerUserId:'u',title:'Fırsat',expectedValue:1000,currency:'TRY',expectedCloseDate:null,productInterest:null,nextAction:null,nextActionAt:null,probability:20,forecastCategory:'potential',expectedMarginPct:null,source:null,priority:'normal',customerNeed:null,decisionProcess:null,competitors:null,lossReason:null,wonAt:null,lostAt:null,archivedAt:null,createdAt:'2026-01-01',updatedAt:'2026-01-01',...overrides})
const activity=(overrides:Partial<SalesActivity>={}):SalesActivity=>({id:'a',companyId:'c',activityType:'task',leadId:'l',partyId:null,contactId:null,opportunityId:null,ownerUserId:'u',assignedTo:null,title:'Takip',description:null,outcome:null,activityAt:'2026-01-01',dueAt:'2026-07-12T10:00:00Z',completedAt:null,nextAction:null,nextActionAt:null,visibility:'sales_team',archivedAt:null,createdAt:'2026-01-01',updatedAt:'2026-01-01',...overrides})

describe('sales execution validation and calculations',()=>{
 it('normalizes and validates leads',()=>{expect(normalizeLeadInput({companyName:' ACME ',email:' INFO@EXAMPLE.COM '}).value).toMatchObject({companyName:'ACME',email:'info@example.com'});expect(normalizeLeadInput({companyName:'',firstName:''}).error).toContain('Firma adı');expect(normalizeLeadInput({firstName:'Ada',email:'bad'}).error).toContain('e-posta')})
 it('requires a disqualification reason and reserves converted state for the RPC',()=>{expect(normalizeLeadInput({firstName:'Ada',status:'disqualified'}).error).toContain('nedeni');expect(normalizeLeadInput({firstName:'Ada',status:'converted'}).error).toContain('atomik')})
 it('validates opportunities',()=>{expect(normalizeOpportunityInput({partyId:'p',pipelineId:'pl',stageId:'s',ownerUserId:'u',title:' ',expectedValue:1}).error).toContain('başlığı');expect(normalizeOpportunityInput({partyId:'p',pipelineId:'pl',stageId:'s',ownerUserId:'u',title:'X',probability:101}).error).toContain('100')})
 it('calculates next action, stale, overdue, probability and weighted value deterministically',()=>{const o=opportunity({expectedCloseDate:'2026-07-01'});const s=stage();expect(opportunityNeedsNextAction(o,s)).toBe(true);expect(opportunityIsStale('2026-07-01',s,new Date('2026-07-12'))).toBe(true);expect(opportunityIsOverdue(o,s,new Date('2026-07-12'))).toBe(true);expect(stageProbability(o,s)).toBe(20);expect(weightedOpportunityValue(o,s)).toBe(200);expect(opportunityState(s)).toBe('open')})
 it('calculates task due and overdue states',()=>{expect(taskIsDueToday(activity(),new Date('2026-07-12T12:00:00Z'))).toBe(true);expect(taskIsOverdue(activity(),new Date('2026-07-13T12:00:00Z'))).toBe(true);expect(taskIsOverdue(activity({completedAt:'2026-07-12T11:00:00Z'}),new Date('2026-07-13'))).toBe(false)})
 it('provides Turkish labels and lead display names',()=>{expect(leadStatusLabels.qualified).toBe('Uygun');expect(activityLabels.meeting).toBe('Toplantı');expect(leadDisplayName({companyName:null,firstName:'Ada',lastName:'Yılmaz'} as SalesLead)).toBe('Ada Yılmaz')})
 it('requires an activity parent',()=>{expect(normalizeActivityInput({activityType:'task',ownerUserId:'u'}).error).toContain('ilişkili');expect(normalizeActivityInput({activityType:'task',ownerUserId:'u',leadId:'l'}).error).toBeNull()})
})

describe('sales execution repository',()=>{
 it('scopes lists to company and excludes archived records by default',async()=>{const c=new Client();await createSalesExecutionRepository(c as unknown as SalesExecutionClient).listSalesLeads('c');expect(c.queries[0].q.ops).toContainEqual(['eq','company_id','c']);expect(c.queries[0].q.ops).toContainEqual(['is','archived_at',null])})
 it('allows archived records only explicitly',async()=>{const c=new Client();await createSalesExecutionRepository(c as unknown as SalesExecutionClient).listSalesOpportunities('c',{includeArchived:true});expect(c.queries[0].q.ops).not.toContainEqual(['is','archived_at',null])})
 it('uses one atomic RPC for existing and new party lead conversion',async()=>{const c=new Client();const repo=createSalesExecutionRepository(c as unknown as SalesExecutionClient);expect((await repo.convertSalesLead('c',{leadId:'l',existingPartyId:'p'})).data).toEqual({partyId:'p',contactId:'c',opportunityId:'o'});expect(c.rpc).toHaveBeenCalledWith('convert_sales_lead',expect.objectContaining({target_company_id:'c',target_lead_id:'l',existing_party_id:'p'}));await repo.convertSalesLead('c',{leadId:'l2',newPartyDisplayName:'Yeni Firma'});expect(c.rpc).toHaveBeenLastCalledWith('convert_sales_lead',expect.objectContaining({new_party_display_name:'Yeni Firma'}))})
 it('uses controlled RPCs for contacts and stage transitions',async()=>{const c=new Client([{data:{id:'o',company_id:'c',party_id:'p',pipeline_id:'pl',stage_id:'s',owner_user_id:'u',title:'X',expected_value:0,currency:'TRY',probability:10,forecast_category:'potential',priority:'normal',created_at:'x',updated_at:'x'},error:null}]);const repo=createSalesExecutionRepository(c as unknown as SalesExecutionClient);await repo.setOpportunityContacts('c','o',[{contactId:'x',isPrimary:true}]);expect(c.rpc).toHaveBeenCalledWith('set_sales_opportunity_contacts',expect.anything());await repo.moveSalesOpportunityStage('c',{opportunityId:'o',destinationStageId:'won'});expect(c.rpc).toHaveBeenCalledWith('move_sales_opportunity_stage',expect.objectContaining({destination_stage_id:'won'}))})
 it('maps errors safely and preserves raw causes',()=>{const cause={code:'42501',message:'secret internal detail'};expect(mapSalesExecutionError(cause)).toEqual({code:'forbidden',message:'Bu işlem için şirket yetkiniz bulunmuyor.',cause});expect(mapSalesExecutionError({code:'23514',message:'loss reason'}).code).toBe('conflict')})
})

describe('sales execution migration contract',()=>{
 it('creates all seven tables and company consistency constraints',()=>{for(const name of ['sales_leads','sales_pipelines','sales_pipeline_stages','sales_opportunities','sales_opportunity_contacts','sales_activities','sales_opportunity_stage_history'])expect(migration).toContain(`create table public.${name}`);expect(migration).toContain('sales_opportunities_stage_company_fk');expect(migration).toContain('sales_activities_contact_company_fk')})
 it('provisions the ordered default pipeline idempotently',()=>{expect(migration).toContain('Standart Satış Pipeline’ı');expect(migration).toContain('on conflict(pipeline_id,stage_key) do nothing');for(const entry of ["'new',1,10,7","'needs_identified',2,20,10","'meeting_completed',3,35,14","'won',8,100","'lost',9,0"])expect(migration).toContain(entry)})
 it('validates members, pipelines, loss reasons, won/lost timestamps and closed reopening',()=>{expect(migration).toContain('Assignee must be an active company member');expect(migration).toContain('Stage must belong to the selected company and pipeline');expect(migration).toContain('Loss reason is required');expect(migration).toContain('new.won_at:=coalesce');expect(migration).toContain('new.lost_at:=coalesce');expect(migration).toContain('Closed opportunities cannot be reopened in V1')})
 it('enforces contact consistency and one primary contact',()=>{expect(migration).toContain('sales_opp_contacts_contact_company_fk');expect(migration).toContain('sales_opp_contacts_one_primary')})
 it('records exactly one trigger-driven history entry per stage update',()=>{expect(migration.match(/create trigger sales_opportunities_history/g)).toHaveLength(1);expect(migration).toContain('insert into public.sales_opportunity_stage_history')})
 it('enforces activity visibility and private isolation',()=>{expect(migration).toContain("visibility='company'");expect(migration).toContain("visibility='sales_team' and public.is_company_operator");expect(migration).toContain("visibility='private' and created_by=auth.uid()")})
 it('keeps accountants read-only, anonymous denied, and hard deletes unavailable',()=>{expect(migration).toContain('grant select,insert,update');expect(migration).not.toMatch(/grant delete/i);expect(migration).toContain('from public,anon,authenticated');expect(migration).toContain('public.is_company_operator(company_id)')})
 it('makes stage history append-only to clients',()=>{expect(migration).toContain('grant select on public.sales_opportunity_stage_history');expect(migration).not.toContain('grant insert on public.sales_opportunity_stage_history')})
 it('implements atomic conversion and rejects duplicate conversion',()=>{expect(migration).toContain('for update');expect(migration).toContain("lead_row.status in ('converted','disqualified')");expect(migration).toContain('update public.sales_leads set status=\'converted\'')})
})
