import { supabase } from '../../../lib/supabase'
import type { LeadConversionInput, LeadConversionResult, OpportunityContactInput, OpportunityStageHistory, SalesActivity, SalesActivityCreateInput, SalesActivityUpdateInput, SalesExecutionError, SalesExecutionResult, SalesLead, SalesLeadCreateInput, SalesLeadUpdateInput, SalesListFilters, SalesOpportunity, SalesOpportunityContact, SalesOpportunityCreateInput, SalesOpportunityUpdateInput, SalesPipeline, SalesPipelineStage, StageTransitionInput } from './types'
import { normalizeActivityInput, normalizeLeadInput, normalizeOpportunityInput } from './validation'

interface Response{data:unknown;error:unknown|null}
interface Query extends PromiseLike<Response>{select(columns:string):Query;eq(column:string,value:unknown):Query;is(column:string,value:null):Query;order(column:string,options?:{ascending?:boolean}):Query;maybeSingle():PromiseLike<Response>}
interface Table{select(columns:string):Query;insert(value:Record<string,unknown>):Query;update(value:Record<string,unknown>):Query}
export interface SalesExecutionClient{from(table:string):Table;rpc(name:string,args:Record<string,unknown>):PromiseLike<Response>}
const rec=(value:unknown)=>typeof value==='object'&&value!==null?value as Record<string,unknown>:{}
const str=(value:unknown)=>typeof value==='string'?value:null
const num=(value:unknown)=>typeof value==='number'?value:Number(value)
const base=(row:Record<string,unknown>)=>({id:String(row.id),companyId:String(row.company_id),archivedAt:str(row.archived_at),createdAt:String(row.created_at),updatedAt:String(row.updated_at)})
const mapLead=(v:unknown):SalesLead=>{const r=rec(v);return{...base(r),leadType:r.lead_type as SalesLead['leadType'],companyName:str(r.company_name),firstName:str(r.first_name),lastName:str(r.last_name),email:str(r.email),phone:str(r.phone),source:str(r.source),productInterest:str(r.product_interest),assignedTo:str(r.assigned_to),status:r.status as SalesLead['status'],estimatedValue:r.estimated_value==null?null:num(r.estimated_value),currency:r.currency as SalesLead['currency'],qualificationNotes:str(r.qualification_notes),nextAction:str(r.next_action),nextActionAt:str(r.next_action_at),disqualificationReason:str(r.disqualification_reason),convertedPartyId:str(r.converted_party_id),convertedContactId:str(r.converted_contact_id),convertedOpportunityId:str(r.converted_opportunity_id),convertedAt:str(r.converted_at)}}
const mapPipeline=(v:unknown):SalesPipeline=>{const r=rec(v);return{...base(r),name:String(r.name),isDefault:Boolean(r.is_default),isActive:Boolean(r.is_active)}}
const mapStage=(v:unknown):SalesPipelineStage=>{const r=rec(v);return{id:String(r.id),companyId:String(r.company_id),pipelineId:String(r.pipeline_id),name:String(r.name),stageKey:String(r.stage_key),position:num(r.position),defaultProbability:num(r.default_probability),staleAfterDays:r.stale_after_days==null?null:num(r.stale_after_days),isClosed:Boolean(r.is_closed),outcome:r.outcome as SalesPipelineStage['outcome'],requiredFields:Array.isArray(r.required_fields)?r.required_fields as string[]:[],recommendedActions:Array.isArray(r.recommended_actions)?r.recommended_actions as string[]:[],createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
const mapOpportunity=(v:unknown):SalesOpportunity=>{const r=rec(v);return{...base(r),partyId:String(r.party_id),pipelineId:String(r.pipeline_id),stageId:String(r.stage_id),ownerUserId:String(r.owner_user_id),title:String(r.title),expectedValue:num(r.expected_value),currency:r.currency as SalesOpportunity['currency'],expectedCloseDate:str(r.expected_close_date),productInterest:str(r.product_interest),nextAction:str(r.next_action),nextActionAt:str(r.next_action_at),probability:num(r.probability),forecastCategory:r.forecast_category as SalesOpportunity['forecastCategory'],expectedMarginPct:r.expected_margin_pct==null?null:num(r.expected_margin_pct),source:str(r.source),priority:r.priority as SalesOpportunity['priority'],customerNeed:str(r.customer_need),decisionProcess:str(r.decision_process),competitors:str(r.competitors),lossReason:str(r.loss_reason),wonAt:str(r.won_at),lostAt:str(r.lost_at)}}
const mapActivity=(v:unknown):SalesActivity=>{const r=rec(v);return{...base(r),activityType:r.activity_type as SalesActivity['activityType'],leadId:str(r.lead_id),partyId:str(r.party_id),contactId:str(r.contact_id),opportunityId:str(r.opportunity_id),ownerUserId:String(r.owner_user_id),assignedTo:str(r.assigned_to),title:str(r.title),description:str(r.description),outcome:str(r.outcome),activityAt:String(r.activity_at),dueAt:str(r.due_at),completedAt:str(r.completed_at),nextAction:str(r.next_action),nextActionAt:str(r.next_action_at),visibility:r.visibility as SalesActivity['visibility']}}
const mapOpportunityContact=(v:unknown):SalesOpportunityContact=>{const r=rec(v);return{id:String(r.id),companyId:String(r.company_id),opportunityId:String(r.opportunity_id),contactId:String(r.contact_id),relationshipRole:str(r.relationship_role),isPrimary:Boolean(r.is_primary),createdAt:String(r.created_at)}}
const fields=(error:unknown)=>rec(error)
export function mapSalesExecutionError(error:unknown):SalesExecutionError{const f=fields(error);const code=String(f.code??'');const message=String(f.message??'').toLowerCase();if(code==='42501'||code==='PGRST301')return{code:'forbidden',message:'Bu işlem için şirket yetkiniz bulunmuyor.',cause:error};if(code==='PGRST116'||code==='P0002')return{code:'not_found',message:'Kayıt bulunamadı.',cause:error};if(code==='23505'||code==='23514'||message.includes('already')||message.includes('cannot'))return{code:'conflict',message:'İşlem mevcut satış kaydı kurallarıyla çelişiyor.',cause:error};return{code:'database',message:'Satış işlemi tamamlanamadı. Lütfen yeniden deneyin.',cause:error}}
const fail=<T>(message:string):SalesExecutionResult<T>=>({data:null,error:{code:'validation',message,cause:null}})
const snake=(input:Record<string,unknown>)=>Object.fromEntries(Object.entries(input).map(([key,value])=>[key.replace(/[A-Z]/g,l=>`_${l.toLowerCase()}`),value]))
function scoped(query:Query,companyId:string,filters:SalesListFilters={}){let q=query.eq('company_id',companyId);if(!filters.includeArchived)q=q.is('archived_at',null);if(filters.status)q=q.eq('status',filters.status);if(filters.assignedTo)q=q.eq('assigned_to',filters.assignedTo);if(filters.ownerUserId)q=q.eq('owner_user_id',filters.ownerUserId);if(filters.partyId)q=q.eq('party_id',filters.partyId);if(filters.opportunityId)q=q.eq('opportunity_id',filters.opportunityId);if(filters.leadId)q=q.eq('lead_id',filters.leadId);return q}

export function createSalesExecutionRepository(client:SalesExecutionClient,now=()=>new Date().toISOString()){
 const list=async<T>(table:string,companyId:string,filters:SalesListFilters,mapper:(v:unknown)=>T,order='updated_at'):Promise<SalesExecutionResult<T[]>>=>{const{data,error}=await scoped(client.from(table).select('*'),companyId,filters).order(order,{ascending:false});return error?{data:null,error:mapSalesExecutionError(error)}:{data:(Array.isArray(data)?data:[]).map(mapper),error:null}}
 const one=async<T>(table:string,companyId:string,id:string,mapper:(v:unknown)=>T,includeArchived=false):Promise<SalesExecutionResult<T>>=>{let q=client.from(table).select('*').eq('company_id',companyId).eq('id',id);if(!includeArchived)q=q.is('archived_at',null);const{data,error}=await q.maybeSingle();if(error)return{data:null,error:mapSalesExecutionError(error)};return data?{data:mapper(data),error:null}:{data:null,error:{code:'not_found',message:'Kayıt bulunamadı.',cause:null}}}
 const insert=async<T>(table:string,companyId:string,payload:Record<string,unknown>,mapper:(v:unknown)=>T):Promise<SalesExecutionResult<T>>=>{const{data,error}=await client.from(table).insert({company_id:companyId,...payload}).select('*').maybeSingle();return error?{data:null,error:mapSalesExecutionError(error)}:{data:mapper(data),error:null}}
 const update=async<T>(table:string,companyId:string,id:string,payload:Record<string,unknown>,mapper:(v:unknown)=>T):Promise<SalesExecutionResult<T>>=>{const{data,error}=await client.from(table).update(payload).eq('company_id',companyId).eq('id',id).select('*').maybeSingle();return error?{data:null,error:mapSalesExecutionError(error)}:data?{data:mapper(data),error:null}:{data:null,error:{code:'not_found',message:'Kayıt bulunamadı.',cause:null}}}
 return{
  listSalesLeads:(companyId:string,filters:SalesListFilters={})=>list('sales_leads',companyId,filters,mapLead),getSalesLead:(companyId:string,id:string,includeArchived=false)=>one('sales_leads',companyId,id,mapLead,includeArchived),
  async createSalesLead(companyId:string,input:SalesLeadCreateInput){const checked=normalizeLeadInput(input);return checked.value?insert('sales_leads',companyId,snake(checked.value as Record<string,unknown>),mapLead):fail<SalesLead>(checked.error!)},
  async updateSalesLead(companyId:string,id:string,input:SalesLeadUpdateInput){const checked=normalizeLeadInput(input);return checked.value?update('sales_leads',companyId,id,snake(checked.value as Record<string,unknown>),mapLead):fail<SalesLead>(checked.error!)},
  archiveSalesLead:(companyId:string,id:string)=>update('sales_leads',companyId,id,{archived_at:now()},mapLead),
  async convertSalesLead(companyId:string,input:LeadConversionInput):Promise<SalesExecutionResult<LeadConversionResult>>{const{data,error}=await client.rpc('convert_sales_lead',{target_company_id:companyId,target_lead_id:input.leadId,existing_party_id:input.existingPartyId??null,new_party_display_name:input.newPartyDisplayName??null,create_contact:input.createContact??true,opportunity_title:input.opportunityTitle??null,target_pipeline_id:input.pipelineId??null,target_stage_id:input.stageId??null,opportunity_expected_value:input.expectedValue??null,opportunity_currency:input.currency??null,opportunity_owner_user_id:input.ownerUserId??null,opportunity_expected_close_date:input.expectedCloseDate??null,opportunity_product_interest:input.productInterest??null,opportunity_next_action:input.nextAction??null,opportunity_next_action_at:input.nextActionAt??null});if(error)return{data:null,error:mapSalesExecutionError(error)};const r=rec(Array.isArray(data)?data[0]:data);return{data:{partyId:String(r.party_id),contactId:str(r.contact_id),opportunityId:String(r.opportunity_id)},error:null}},
  listSalesPipelines:(companyId:string,filters:SalesListFilters={})=>list('sales_pipelines',companyId,filters,mapPipeline),
  async getDefaultSalesPipeline(companyId:string){const{data,error}=await client.from('sales_pipelines').select('*').eq('company_id',companyId).eq('is_default',true).eq('is_active',true).is('archived_at',null).maybeSingle();return error?{data:null,error:mapSalesExecutionError(error)}:data?{data:mapPipeline(data),error:null}:{data:null,error:{code:'not_found',message:'Varsayılan pipeline bulunamadı.',cause:null}}},
  async listSalesPipelineStages(companyId:string,pipelineId:string){const{data,error}=await client.from('sales_pipeline_stages').select('*').eq('company_id',companyId).eq('pipeline_id',pipelineId).order('position',{ascending:true});return error?{data:null,error:mapSalesExecutionError(error)}:{data:(Array.isArray(data)?data:[]).map(mapStage),error:null}},
  listSalesOpportunities:(companyId:string,filters:SalesListFilters={})=>list('sales_opportunities',companyId,filters,mapOpportunity),getSalesOpportunity:(companyId:string,id:string,includeArchived=false)=>one('sales_opportunities',companyId,id,mapOpportunity,includeArchived),
  async createSalesOpportunity(companyId:string,input:SalesOpportunityCreateInput){const checked=normalizeOpportunityInput(input);return checked.value?insert('sales_opportunities',companyId,snake(checked.value as unknown as Record<string,unknown>),mapOpportunity):fail<SalesOpportunity>(checked.error!)},
  async updateSalesOpportunity(companyId:string,id:string,input:SalesOpportunityUpdateInput){const checked=normalizeOpportunityInput(input);return checked.value?update('sales_opportunities',companyId,id,snake(checked.value as Record<string,unknown>),mapOpportunity):fail<SalesOpportunity>(checked.error!)},
  archiveSalesOpportunity:(companyId:string,id:string)=>update('sales_opportunities',companyId,id,{archived_at:now()},mapOpportunity),
  async listOpportunityContacts(companyId:string,opportunityId:string):Promise<SalesExecutionResult<SalesOpportunityContact[]>>{const{data,error}=await client.from('sales_opportunity_contacts').select('*').eq('company_id',companyId).eq('opportunity_id',opportunityId).order('created_at',{ascending:true});return error?{data:null,error:mapSalesExecutionError(error)}:{data:(Array.isArray(data)?data:[]).map(mapOpportunityContact),error:null}},
  async setOpportunityContacts(companyId:string,opportunityId:string,contacts:OpportunityContactInput[]){const{error}=await client.rpc('set_sales_opportunity_contacts',{target_company_id:companyId,target_opportunity_id:opportunityId,intended_contacts:contacts.map(c=>({contact_id:c.contactId,relationship_role:c.relationshipRole??null,is_primary:c.isPrimary??false}))});return error?{data:null,error:mapSalesExecutionError(error)}:{data:null,error:null}},
  async moveSalesOpportunityStage(companyId:string,input:StageTransitionInput){const{data,error}=await client.rpc('move_sales_opportunity_stage',{target_company_id:companyId,target_opportunity_id:input.opportunityId,destination_stage_id:input.destinationStageId,transition_reason:input.reason??null,new_loss_reason:input.lossReason??null,new_next_action:input.nextAction??null,new_next_action_at:input.nextActionAt??null});return error?{data:null,error:mapSalesExecutionError(error)}:{data:mapOpportunity(data),error:null}},
  async listOpportunityStageHistory(companyId:string,opportunityId:string):Promise<SalesExecutionResult<OpportunityStageHistory[]>>{const{data,error}=await client.from('sales_opportunity_stage_history').select('*').eq('company_id',companyId).eq('opportunity_id',opportunityId).order('changed_at',{ascending:false});if(error)return{data:null,error:mapSalesExecutionError(error)};return{data:(Array.isArray(data)?data:[]).map(v=>{const r=rec(v);return{id:String(r.id),companyId:String(r.company_id),opportunityId:String(r.opportunity_id),fromStageId:str(r.from_stage_id),toStageId:String(r.to_stage_id),changedBy:String(r.changed_by),changedAt:String(r.changed_at),reason:str(r.reason),daysInPreviousStage:r.days_in_previous_stage==null?null:num(r.days_in_previous_stage)}}),error:null}},
  listSalesActivities:(companyId:string,filters:SalesListFilters={})=>list('sales_activities',companyId,filters,mapActivity,'activity_at'),
  async createSalesActivity(companyId:string,input:SalesActivityCreateInput){const checked=normalizeActivityInput(input);return checked.value?insert('sales_activities',companyId,snake(checked.value as Record<string,unknown>),mapActivity):fail<SalesActivity>(checked.error!)},
  updateSalesActivity:(companyId:string,id:string,input:SalesActivityUpdateInput)=>update('sales_activities',companyId,id,snake(input as Record<string,unknown>),mapActivity),
  completeSalesTask:(companyId:string,id:string)=>update('sales_activities',companyId,id,{completed_at:now()},mapActivity),archiveSalesActivity:(companyId:string,id:string)=>update('sales_activities',companyId,id,{archived_at:now()},mapActivity),
 }
}
export const salesExecutionRepository=createSalesExecutionRepository(supabase as unknown as SalesExecutionClient)
export const {listSalesLeads,getSalesLead,createSalesLead,updateSalesLead,archiveSalesLead,convertSalesLead,listSalesPipelines,getDefaultSalesPipeline,listSalesPipelineStages,listSalesOpportunities,getSalesOpportunity,createSalesOpportunity,updateSalesOpportunity,archiveSalesOpportunity,listOpportunityContacts,setOpportunityContacts,moveSalesOpportunityStage,listOpportunityStageHistory,listSalesActivities,createSalesActivity,updateSalesActivity,completeSalesTask,archiveSalesActivity}=salesExecutionRepository
