import type { SalesActivityCreateInput, SalesLeadCreateInput, SalesLeadUpdateInput, SalesOpportunityCreateInput, SalesOpportunityUpdateInput } from './types'
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/
export const optional=(value:string|null|undefined)=>value?.trim()||null
export const normalizedEmail=(value:string|null|undefined)=>optional(value)?.toLocaleLowerCase('en-US')??null
export function normalizeLeadInput<T extends SalesLeadCreateInput|SalesLeadUpdateInput>(input:T):{value:T|null;error:string|null}{
 const value={...input} as T; if('companyName'in value)value.companyName=optional(value.companyName);if('firstName'in value)value.firstName=optional(value.firstName);if('lastName'in value)value.lastName=optional(value.lastName);if('email'in value)value.email=normalizedEmail(value.email);if('phone'in value)value.phone=optional(value.phone);if('source'in value)value.source=optional(value.source);if('productInterest'in value)value.productInterest=optional(value.productInterest);if('qualificationNotes'in value)value.qualificationNotes=optional(value.qualificationNotes);if('nextAction'in value)value.nextAction=optional(value.nextAction);if('disqualificationReason'in value)value.disqualificationReason=optional(value.disqualificationReason)
 if(('companyName'in value||'firstName'in value)&&!value.companyName&&!value.firstName)return{value:null,error:'Firma adı veya kişi adı gereklidir.'};if(value.email&&!emailPattern.test(value.email))return{value:null,error:'Geçerli bir e-posta adresi girilmelidir.'};if(value.estimatedValue!=null&&value.estimatedValue<0)return{value:null,error:'Tahmini değer negatif olamaz.'};if(value.status==='disqualified'&&!value.disqualificationReason)return{value:null,error:'Uygun bulunmama nedeni gereklidir.'};if(value.status==='converted')return{value:null,error:'Dönüştürülmüş durum yalnız atomik dönüşümle atanabilir.'};return{value,error:null}
}
export function normalizeOpportunityInput<T extends SalesOpportunityCreateInput|SalesOpportunityUpdateInput>(input:T):{value:T|null;error:string|null}{const value={...input} as T;if('title'in value){value.title=value.title?.trim();if(!value.title)return{value:null,error:'Fırsat başlığı gereklidir.'}}if(value.expectedValue!=null&&value.expectedValue<0)return{value:null,error:'Beklenen değer negatif olamaz.'};if(value.probability!=null&&(value.probability<0||value.probability>100))return{value:null,error:'Olasılık 0 ile 100 arasında olmalıdır.'};return{value,error:null}}
export function normalizeActivityInput(input:SalesActivityCreateInput){const value={...input,title:optional(input.title),description:optional(input.description),outcome:optional(input.outcome),nextAction:optional(input.nextAction)};if(!value.leadId&&!value.partyId&&!value.opportunityId)return{value:null,error:'Aktivite bir potansiyel müşteri, firma veya fırsatla ilişkili olmalıdır.'};return{value,error:null}}
