import type { FinanceInvoice, FinancePayment, PartyReceivableSummary, ReceivableAgingBucket, ReceivableScheduleEntry } from "./types";

const day=86_400_000;
const localDay=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),value.getDate()).getTime();
export const invoicePaidAmount=(grandTotal:number,outstanding:number)=>Math.max(0,grandTotal-outstanding);
export const invoiceOutstandingAmount=(grandTotal:number,paid:number)=>Math.max(0,grandTotal-paid);
export const invoicePaymentPercentage=(grandTotal:number,paid:number)=>grandTotal>0?Math.min(100,Math.max(0,paid)/grandTotal*100):100;
export function daysUntilInvoiceDue(dueDate:string|null,now=new Date()){if(!dueDate)return null;return Math.ceil((new Date(`${dueDate}T00:00:00`).getTime()-localDay(now))/day)}
export const isInvoiceOverdue=(invoice:Pick<FinanceInvoice,"status"|"outstandingAmount"|"dueDate">,now=new Date())=>["issued","partially_paid"].includes(invoice.status)&&invoice.outstandingAmount>0&&(daysUntilInvoiceDue(invoice.dueDate,now)??0)<0;
export const invoiceDaysOverdue=(invoice:Pick<FinanceInvoice,"status"|"outstandingAmount"|"dueDate">,now=new Date())=>isInvoiceOverdue(invoice,now)?Math.abs(daysUntilInvoiceDue(invoice.dueDate,now)??0):0;
export const isFinanceInvoiceTerminal=(status:FinanceInvoice["status"])=>status==="paid"||status==="cancelled";
export function receivableAgingBucket(daysOverdue:number):ReceivableAgingBucket{return daysOverdue<=0?"current":daysOverdue<=30?"1_30":daysOverdue<=60?"31_60":daysOverdue<=90?"61_90":"90_plus"}
export function receivableSchedule(invoices:FinanceInvoice[],now=new Date()):ReceivableScheduleEntry[]{return invoices.filter(x=>x.outstandingAmount>0&&["issued","partially_paid"].includes(x.status)).map(x=>{const days=invoiceDaysOverdue(x,now);return {invoiceId:x.id,invoiceNumber:x.invoiceNumber,partyId:x.partyId,partyDisplayName:x.partyDisplayName,dueDate:x.dueDate,currency:x.currency,outstandingAmount:x.outstandingAmount,overdue:days>0,daysOverdue:days,agingBucket:receivableAgingBucket(days)}}).sort((a,b)=>(a.dueDate??"9999").localeCompare(b.dueDate??"9999"))}
export function partyReceivableSummary(partyId:string,invoices:FinanceInvoice[],payments:FinancePayment[],now=new Date()):PartyReceivableSummary{const mine=invoices.filter(x=>x.partyId===partyId);const schedule=receivableSchedule(mine,now);const partyPayments=payments.filter(x=>x.partyId===partyId&&x.direction==="inflow");const byCurrency:PartyReceivableSummary["byCurrency"]={};for(const entry of schedule){const totals=byCurrency[entry.currency]??{totalOpenReceivable:0,overdueReceivable:0,openInvoiceCount:0};totals.totalOpenReceivable+=entry.outstandingAmount;totals.overdueReceivable+=entry.overdue?entry.outstandingAmount:0;totals.openInvoiceCount+=1;byCurrency[entry.currency]=totals}return {partyId,byCurrency,openInvoiceCount:schedule.length,lastInvoiceDate:mine.map(x=>x.issueDate).sort().at(-1)??null,lastCollectionDate:partyPayments.map(x=>x.paymentDate).sort().at(-1)??null,paymentHistoryCount:partyPayments.length,schedule}}
export const financeAccountBalance=(openingBalance:number,payments:FinancePayment[])=>payments.reduce((sum,p)=>sum+(p.direction==="inflow"?p.amount:-p.amount),openingBalance);
