import { supabase } from "../../../lib/supabase";
import { financeAccountBalance, partyReceivableSummary, receivableSchedule } from "./financeCalculations";
import type { CreateSalesInvoiceFromOrderInput, CreateSalesInvoiceFromOrderResult, FinanceAccount, FinanceAccountCreateInput, FinanceAccountFilters, FinanceInvoice, FinanceInvoiceFilters, FinanceInvoiceItem, FinanceInvoiceStatusHistory, FinanceInvoiceTransitionInput, FinancePayment, FinancePaymentAllocation, FinancePaymentFilters, FinanceRepositoryError, FinanceRepositoryResult, PartyReceivableSummary, ReceivableScheduleEntry, RecordCustomerCollectionInput, RecordCustomerCollectionResult } from "./types";
import { normalizeCustomerCollection, normalizeFinanceAccount, normalizeInvoiceConversion, normalizeInvoiceTransition } from "./validation";

interface Response{data:unknown;error:unknown|null}
interface Query extends PromiseLike<Response>{select(value:string):Query;eq(column:string,value:unknown):Query;is(column:string,value:null):Query;gte(column:string,value:unknown):Query;lte(column:string,value:unknown):Query;order(column:string,options?:{ascending?:boolean}):Query;maybeSingle():PromiseLike<Response>}
interface Table{select(value:string):Query}
export interface FinanceDataClient{from(table:string):Table;rpc(name:string,args:Record<string,unknown>):PromiseLike<Response>}
const record=(value:unknown):Record<string,unknown>=>typeof value==="object"&&value!==null?value as Record<string,unknown>:{};
const nullable=(value:unknown)=>typeof value==="string"?value:null;
const number=(value:unknown)=>typeof value==="number"?value:Number(value);
const account=(value:unknown):FinanceAccount=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),name:String(r.name),accountType:r.account_type as FinanceAccount["accountType"],currency:r.currency as FinanceAccount["currency"],iban:nullable(r.iban),openingBalance:number(r.opening_balance),archivedAt:nullable(r.archived_at),createdBy:String(r.created_by),updatedBy:String(r.updated_by),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}};
const invoice=(value:unknown):FinanceInvoice=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),invoiceNumber:String(r.invoice_number),invoiceType:r.invoice_type as FinanceInvoice["invoiceType"],sourceSalesOrderId:nullable(r.source_sales_order_id),partyId:String(r.party_id),contactId:nullable(r.contact_id),opportunityId:nullable(r.opportunity_id),ownerUserId:String(r.owner_user_id),status:r.status as FinanceInvoice["status"],currency:r.currency as FinanceInvoice["currency"],issueDate:String(r.issue_date),dueDate:nullable(r.due_date),paymentTerms:nullable(r.payment_terms),customerNotes:nullable(r.customer_notes),internalNotes:nullable(r.internal_notes),partyDisplayName:String(r.party_display_name),partyTaxId:nullable(r.party_tax_id),partyTaxOffice:nullable(r.party_tax_office),partyAddress:nullable(r.party_address),contactDisplayName:nullable(r.contact_display_name),contactEmail:nullable(r.contact_email),contactPhone:nullable(r.contact_phone),subtotal:number(r.subtotal),discountTotal:number(r.discount_total),taxTotal:number(r.tax_total),otherTaxTotal:number(r.other_tax_total),grandTotal:number(r.grand_total),paidAmount:number(r.paid_amount),outstandingAmount:number(r.outstanding_amount),issuedAt:nullable(r.issued_at),paidAt:nullable(r.paid_at),cancelledAt:nullable(r.cancelled_at),cancellationReason:nullable(r.cancellation_reason),archivedAt:nullable(r.archived_at),createdBy:String(r.created_by),updatedBy:String(r.updated_by),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}};
const item=(value:unknown):FinanceInvoiceItem=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),invoiceId:String(r.invoice_id),sourceSalesOrderItemId:nullable(r.source_sales_order_item_id),position:number(r.position),itemCode:nullable(r.item_code),description:String(r.description),quantity:number(r.quantity),unit:String(r.unit),unitPrice:number(r.unit_price),discountType:r.discount_type as FinanceInvoiceItem["discountType"],discountValue:number(r.discount_value),vatRate:number(r.vat_rate),otherTaxRate:number(r.other_tax_rate),lineSubtotal:number(r.line_subtotal),lineDiscount:number(r.line_discount),lineTax:number(r.line_tax),lineOtherTax:number(r.line_other_tax),lineTotal:number(r.line_total),createdAt:String(r.created_at)}};
const history=(value:unknown):FinanceInvoiceStatusHistory=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),invoiceId:String(r.invoice_id),fromStatus:r.from_status as FinanceInvoiceStatusHistory["fromStatus"],toStatus:r.to_status as FinanceInvoiceStatusHistory["toStatus"],changedBy:String(r.changed_by),changedAt:String(r.changed_at),reason:nullable(r.reason)}};
const payment=(value:unknown):FinancePayment=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),paymentNumber:String(r.payment_number),direction:r.direction as FinancePayment["direction"],partyId:String(r.party_id),accountId:String(r.account_id),paymentDate:String(r.payment_date),currency:r.currency as FinancePayment["currency"],amount:number(r.amount),paymentMethod:r.payment_method as FinancePayment["paymentMethod"],externalReference:nullable(r.external_reference),note:nullable(r.note),postedAt:String(r.posted_at),createdBy:String(r.created_by),createdAt:String(r.created_at)}};
const allocation=(value:unknown):FinancePaymentAllocation=>{const r=record(value);return {id:String(r.id),companyId:String(r.company_id),paymentId:String(r.payment_id),invoiceId:String(r.invoice_id),allocatedAmount:number(r.allocated_amount),createdAt:String(r.created_at)}};

export function mapFinanceError(error:unknown):FinanceRepositoryError{const r=record(error);const code=String(r.code??"");const message=String(r.message??"").toLowerCase();if(code==="42501"||code==="PGRST301")return {code:"forbidden",message:"Bu Finans işlemi için şirket yetkiniz bulunmuyor.",cause:error};if(code==="PGRST116"||code==="P0002")return {code:"not_found",message:"Finans kaydı bulunamadı.",cause:error};if(code==="23505"&&message.includes("source_sales_order"))return {code:"conflict",message:"Bu satış siparişi için fatura zaten oluşturulmuş.",cause:error};if(code==="23505"&&message.includes("iban"))return {code:"conflict",message:"Bu IBAN şirketinizde başka bir hesapta kullanılıyor.",cause:error};if(["23505","23514","22023"].includes(code))return {code:"conflict",message:"Finans işlemi mevcut kayıt veya doğrulama kurallarıyla çelişiyor.",cause:error};return {code:"database",message:"Finans işlemi tamamlanamadı. Lütfen yeniden deneyin.",cause:error}}
const invalid=<T>(message:string):FinanceRepositoryResult<T>=>({data:null,error:{code:"validation",message,cause:null}});

export function createFinanceRepository(client:FinanceDataClient){
  async function list<T>(table:string,companyId:string,mapper:(value:unknown)=>T,configure?:(query:Query)=>Query):Promise<FinanceRepositoryResult<T[]>>{let query=client.from(table).select("*").eq("company_id",companyId);if(configure)query=configure(query);const {data,error}=await query;return error?{data:null,error:mapFinanceError(error)}:{data:(Array.isArray(data)?data:[]).map(mapper),error:null}}
  async function one<T>(table:string,companyId:string,id:string,mapper:(value:unknown)=>T):Promise<FinanceRepositoryResult<T>>{const {data,error}=await client.from(table).select("*").eq("company_id",companyId).eq("id",id).maybeSingle();return error?{data:null,error:mapFinanceError(error)}:data?{data:mapper(data),error:null}:{data:null,error:{code:"not_found",message:"Finans kaydı bulunamadı.",cause:null}}}
  const repo={
    listFinanceAccounts:(companyId:string,filters:FinanceAccountFilters={})=>list("finance_accounts",companyId,account,q=>{let x=q;if(!filters.includeArchived)x=x.is("archived_at",null);if(filters.accountType)x=x.eq("account_type",filters.accountType);if(filters.currency)x=x.eq("currency",filters.currency);return x.order("name",{ascending:true})}),
    getFinanceAccount:(companyId:string,id:string)=>one("finance_accounts",companyId,id,account),
    async createFinanceAccount(companyId:string,input:FinanceAccountCreateInput):Promise<FinanceRepositoryResult<FinanceAccount>>{const checked=normalizeFinanceAccount(input);if(!checked.value)return invalid(checked.error!);const v=checked.value;const result=await client.rpc("create_finance_account",{target_company_id:companyId,account_name:v.name,account_type_value:v.accountType,account_currency:v.currency,account_iban:v.iban,account_opening_balance:v.openingBalance});if(result.error)return {data:null,error:mapFinanceError(result.error)};return one("finance_accounts",companyId,String(result.data),account)},
    async archiveFinanceAccount(companyId:string,id:string):Promise<FinanceRepositoryResult<FinanceAccount>>{const {data,error}=await client.rpc("archive_finance_account",{target_company_id:companyId,target_account_id:id});return error?{data:null,error:mapFinanceError(error)}:{data:account(data),error:null}},
    listFinanceInvoices:(companyId:string,filters:FinanceInvoiceFilters={})=>list("finance_invoices",companyId,invoice,q=>{let x=q;if(!filters.includeArchived)x=x.is("archived_at",null);if(filters.status)x=x.eq("status",filters.status);if(filters.partyId)x=x.eq("party_id",filters.partyId);if(filters.sourceSalesOrderId)x=x.eq("source_sales_order_id",filters.sourceSalesOrderId);if(filters.ownerUserId)x=x.eq("owner_user_id",filters.ownerUserId);if(filters.currency)x=x.eq("currency",filters.currency);return x.order("issue_date",{ascending:false})}),
    getFinanceInvoice:(companyId:string,id:string)=>one("finance_invoices",companyId,id,invoice),
    async getFinanceInvoiceForSalesOrder(companyId:string,salesOrderId:string):Promise<FinanceRepositoryResult<FinanceInvoice|null>>{const {data,error}=await client.from("finance_invoices").select("*").eq("company_id",companyId).eq("source_sales_order_id",salesOrderId).maybeSingle();return error?{data:null,error:mapFinanceError(error)}:{data:data?invoice(data):null,error:null}},
    listFinanceInvoiceItems:(companyId:string,invoiceId:string)=>list("finance_invoice_items",companyId,item,q=>q.eq("invoice_id",invoiceId).order("position",{ascending:true})),
    listFinanceInvoiceStatusHistory:(companyId:string,invoiceId:string)=>list("finance_invoice_status_history",companyId,history,q=>q.eq("invoice_id",invoiceId).order("changed_at",{ascending:true})),
    async createSalesInvoiceFromSalesOrder(companyId:string,input:CreateSalesInvoiceFromOrderInput):Promise<FinanceRepositoryResult<CreateSalesInvoiceFromOrderResult>>{const checked=normalizeInvoiceConversion(input);if(!checked.value)return invalid(checked.error!);const v=checked.value;const {data,error}=await client.rpc("create_sales_invoice_from_sales_order",{target_company_id:companyId,target_sales_order_id:v.salesOrderId,requested_issue_date:v.issueDate,requested_due_date:v.dueDate,requested_customer_note:v.customerNote,requested_internal_note:v.internalNote});if(error)return {data:null,error:mapFinanceError(error)};const r=record(Array.isArray(data)?data[0]:data);return {data:{invoiceId:String(r.invoice_id),invoiceNumber:String(r.invoice_number)},error:null}},
    async transitionFinanceInvoiceStatus(companyId:string,input:FinanceInvoiceTransitionInput):Promise<FinanceRepositoryResult<FinanceInvoice>>{const checked=normalizeInvoiceTransition(input);if(!checked.value)return invalid(checked.error!);const v=checked.value;const {data,error}=await client.rpc("transition_finance_invoice_status",{target_company_id:companyId,target_invoice_id:v.invoiceId,destination_status:v.destinationStatus,transition_reason:v.reason});return error?{data:null,error:mapFinanceError(error)}:{data:invoice(data),error:null}},
    async archiveFinanceInvoice(companyId:string,id:string):Promise<FinanceRepositoryResult<FinanceInvoice>>{const {data,error}=await client.rpc("archive_finance_invoice",{target_company_id:companyId,target_invoice_id:id});return error?{data:null,error:mapFinanceError(error)}:{data:invoice(data),error:null}},
    listFinancePayments:(companyId:string,filters:FinancePaymentFilters={})=>list("finance_payments",companyId,payment,q=>{let x=q;if(filters.partyId)x=x.eq("party_id",filters.partyId);if(filters.accountId)x=x.eq("account_id",filters.accountId);if(filters.fromDate)x=x.gte("payment_date",filters.fromDate);if(filters.toDate)x=x.lte("payment_date",filters.toDate);return x.order("payment_date",{ascending:false})}),
    getFinancePayment:(companyId:string,id:string)=>one("finance_payments",companyId,id,payment),
    listFinancePaymentAllocations:(companyId:string,paymentId:string)=>list("finance_payment_allocations",companyId,allocation,q=>q.eq("payment_id",paymentId).order("created_at",{ascending:true})),
    async recordCustomerCollection(companyId:string,input:RecordCustomerCollectionInput):Promise<FinanceRepositoryResult<RecordCustomerCollectionResult>>{const checked=normalizeCustomerCollection(input);if(!checked.value)return invalid(checked.error!);const v=checked.value;const {data,error}=await client.rpc("record_customer_collection",{target_company_id:companyId,target_party_id:v.partyId,target_account_id:v.accountId,requested_payment_date:v.paymentDate,requested_payment_method:v.paymentMethod,requested_external_reference:v.externalReference,requested_note:v.note,allocations:v.allocations.map(x=>({invoice_id:x.invoiceId,allocated_amount:x.allocatedAmount}))});if(error)return {data:null,error:mapFinanceError(error)};const r=record(Array.isArray(data)?data[0]:data);const affected=Array.isArray(r.affected_invoices)?r.affected_invoices.map(x=>{const row=record(x);return {invoiceId:String(row.invoice_id),status:String(row.status) as FinanceInvoice["status"]}}):[];return {data:{paymentId:String(r.payment_id),paymentNumber:String(r.payment_number),amount:number(r.amount),affectedInvoices:affected,message:"Tahsilat başarıyla kaydedildi."},error:null}},
    async getPartyReceivableSummary(companyId:string,partyId:string,now=new Date()):Promise<FinanceRepositoryResult<PartyReceivableSummary>>{const [invoices,payments]=await Promise.all([repo.listFinanceInvoices(companyId,{partyId,includeArchived:false}),repo.listFinancePayments(companyId,{partyId})]);if(invoices.error||payments.error)return {data:null,error:(invoices.error??payments.error)!};return {data:partyReceivableSummary(partyId,invoices.data,payments.data,now),error:null}},
    async listPartyFinanceInvoices(companyId:string,partyId:string,includeArchived=false){return repo.listFinanceInvoices(companyId,{partyId,includeArchived})},
    async listReceivableSchedule(companyId:string,partyId?:string,now=new Date()):Promise<FinanceRepositoryResult<ReceivableScheduleEntry[]>>{const result=await repo.listFinanceInvoices(companyId,{partyId,includeArchived:false});return result.error?result:{data:receivableSchedule(result.data,now),error:null}},
    async getFinanceAccountBalance(companyId:string,accountId:string):Promise<FinanceRepositoryResult<number>>{const [a,p]=await Promise.all([repo.getFinanceAccount(companyId,accountId),repo.listFinancePayments(companyId,{accountId})]);if(a.error||p.error)return {data:null,error:(a.error??p.error)!};return {data:financeAccountBalance(a.data.openingBalance,p.data),error:null}},
  };return repo;
}

const repository=createFinanceRepository(supabase as unknown as FinanceDataClient);
export const listFinanceAccounts=repository.listFinanceAccounts;
export const getFinanceAccount=repository.getFinanceAccount;
export const createFinanceAccount=repository.createFinanceAccount;
export const archiveFinanceAccount=repository.archiveFinanceAccount;
export const listFinanceInvoices=repository.listFinanceInvoices;
export const getFinanceInvoice=repository.getFinanceInvoice;
export const getFinanceInvoiceForSalesOrder=repository.getFinanceInvoiceForSalesOrder;
export const listFinanceInvoiceItems=repository.listFinanceInvoiceItems;
export const listFinanceInvoiceStatusHistory=repository.listFinanceInvoiceStatusHistory;
export const createSalesInvoiceFromSalesOrder=repository.createSalesInvoiceFromSalesOrder;
export const transitionFinanceInvoiceStatus=repository.transitionFinanceInvoiceStatus;
export const archiveFinanceInvoice=repository.archiveFinanceInvoice;
export const listFinancePayments=repository.listFinancePayments;
export const getFinancePayment=repository.getFinancePayment;
export const listFinancePaymentAllocations=repository.listFinancePaymentAllocations;
export const recordCustomerCollection=repository.recordCustomerCollection;
export const getPartyReceivableSummary=repository.getPartyReceivableSummary;
export const listPartyFinanceInvoices=repository.listPartyFinanceInvoices;
export const listReceivableSchedule=repository.listReceivableSchedule;
export const getFinanceAccountBalance=repository.getFinanceAccountBalance;
