import { describe,expect,it,vi } from "vitest";
import migration from "../../../../supabase/migrations/20260714190000_finance_integration_data_foundation_v1.sql?raw";
import financeStoreSource from "../financeStore.ts?raw";
import cariStoreSource from "../cari/cariStore.ts?raw";
import ledgerBridgeSource from "../muhasebe/bridge.ts?raw";
import { createFinanceRepository,mapFinanceError,type FinanceDataClient } from "./financeRepository";
import { financeAccountBalance, invoiceDaysOverdue, invoiceOutstandingAmount, invoicePaidAmount, invoicePaymentPercentage, isFinanceInvoiceTerminal, isInvoiceOverdue, partyReceivableSummary, receivableAgingBucket, receivableSchedule } from "./financeCalculations";
import { normalizeCustomerCollection,normalizeFinanceAccount,normalizeIban,normalizeInvoiceConversion,normalizeInvoiceTransition } from "./validation";
import { financeInvoiceStatusLabels,financePaymentMethodLabels } from "./financeViewModel";
import { FINANCE_LEGACY_BOUNDARY } from "./legacyBoundary";
import type { FinanceInvoice,FinancePayment } from "./types";

class Query implements PromiseLike<{data:unknown;error:unknown|null}>{ops:Array<[string,...unknown[]]>=[];constructor(private response={data:[] as unknown,error:null as unknown|null}){}select(v:string){this.ops.push(["select",v]);return this}eq(a:string,b:unknown){this.ops.push(["eq",a,b]);return this}is(a:string,b:null){this.ops.push(["is",a,b]);return this}gte(a:string,b:unknown){this.ops.push(["gte",a,b]);return this}lte(a:string,b:unknown){this.ops.push(["lte",a,b]);return this}order(a:string,b?:{ascending?:boolean}){this.ops.push(["order",a,b]);return this}maybeSingle(){this.ops.push(["maybeSingle"]);return Promise.resolve(this.response)}then<A={data:unknown;error:unknown|null},B=never>(ok?:((v:{data:unknown;error:unknown|null})=>A|PromiseLike<A>)|null,bad?:((r:unknown)=>B|PromiseLike<B>)|null){return Promise.resolve(this.response).then(ok,bad)}}
class Client{queries:Array<{table:string;query:Query}>=[];rpc=vi.fn(async(name:string,args:Record<string,unknown>)=>{void args;return {data:name==="create_finance_account"?"account-1":name==="create_sales_invoice_from_sales_order"?[{invoice_id:"invoice-1",invoice_number:"FTR-2026-000001"}]:name==="record_customer_collection"?[{payment_id:"payment-1",payment_number:"THS-2026-000001",amount:100,affected_invoices:[{invoice_id:"invoice-1",status:"paid"}]}]:invoiceRow,error:null}});constructor(private responses:Array<{data:unknown;error:unknown|null}>=[]){}from(table:string){const query=new Query(this.responses.shift());this.queries.push({table,query});return query}}
const invoiceRow={id:"invoice-1",company_id:"company-1",invoice_number:"FTR-2026-000001",invoice_type:"sales",source_sales_order_id:"order-1",party_id:"party-1",contact_id:null,opportunity_id:null,owner_user_id:"user-1",status:"issued",currency:"TRY",issue_date:"2026-07-01",due_date:"2026-07-10",payment_terms:null,customer_notes:null,internal_notes:null,party_display_name:"Örnek",party_tax_id:null,party_tax_office:null,party_address:null,contact_display_name:null,contact_email:null,contact_phone:null,subtotal:100,discount_total:0,tax_total:20,other_tax_total:0,grand_total:120,paid_amount:20,outstanding_amount:100,issued_at:"2026-07-01",paid_at:null,cancelled_at:null,cancellation_reason:null,archived_at:null,created_by:"user-1",updated_by:"user-1",created_at:"2026-07-01",updated_at:"2026-07-01"};
const invoice=(changes:Partial<FinanceInvoice>={}):FinanceInvoice=>({id:"invoice-1",companyId:"company-1",invoiceNumber:"FTR-2026-000001",invoiceType:"sales",sourceSalesOrderId:"order-1",partyId:"party-1",contactId:null,opportunityId:null,ownerUserId:"user-1",status:"issued",currency:"TRY",issueDate:"2026-07-01",dueDate:"2026-07-10",paymentTerms:null,customerNotes:null,internalNotes:null,partyDisplayName:"Örnek",partyTaxId:null,partyTaxOffice:null,partyAddress:null,contactDisplayName:null,contactEmail:null,contactPhone:null,subtotal:100,discountTotal:0,taxTotal:20,otherTaxTotal:0,grandTotal:120,paidAmount:20,outstandingAmount:100,issuedAt:"2026-07-01",paidAt:null,cancelledAt:null,cancellationReason:null,archivedAt:null,createdBy:"user-1",updatedBy:"user-1",createdAt:"2026-07-01",updatedAt:"2026-07-01",...changes});
const payment=(changes:Partial<FinancePayment>={}):FinancePayment=>({id:"payment-1",companyId:"company-1",paymentNumber:"THS-2026-000001",direction:"inflow",partyId:"party-1",accountId:"account-1",paymentDate:"2026-07-12",currency:"TRY",amount:20,paymentMethod:"bank_transfer",externalReference:null,note:null,postedAt:"2026-07-12",createdBy:"user-1",createdAt:"2026-07-12",...changes});

describe("finance validation",()=>{
  it("normalizes account and IBAN fields",()=>{expect(normalizeIban(" tr12 000-1 ")).toBe("TR120001");expect(normalizeFinanceAccount({name:" Kasa ",accountType:"cash",currency:"TRY",openingBalance:10}).value).toMatchObject({name:"Kasa",openingBalance:10})});
  it("rejects invalid accounts, currencies and IBAN",()=>{expect(normalizeFinanceAccount({name:"",accountType:"bank",currency:"TRY"}).error).toContain("adı");expect(normalizeFinanceAccount({name:"B",accountType:"bank",currency:"JPY" as never}).error).toContain("para birimi");expect(normalizeFinanceAccount({name:"B",accountType:"bank",currency:"TRY",iban:"TR1"}).error).toContain("IBAN")});
  it("validates order conversion and due date",()=>{expect(normalizeInvoiceConversion({salesOrderId:"",dueDate:"2026-07-20"}).error).toContain("siparişi");expect(normalizeInvoiceConversion({salesOrderId:"order-1",issueDate:"2026-07-20",dueDate:"2026-07-10"}).error).toContain("önce")});
  it("requires cancellation reason and blocks allocation duplicates",()=>{expect(normalizeInvoiceTransition({invoiceId:"i",destinationStatus:"cancelled"}).error).toContain("nedeni");expect(normalizeCustomerCollection({partyId:"p",accountId:"a",paymentDate:"2026-07-14",paymentMethod:"cash",allocations:[{invoiceId:"i",allocatedAmount:1},{invoiceId:"i",allocatedAmount:2}]}).error).toContain("yalnız bir")});
  it("requires positive allocated amounts and supported methods",()=>{expect(normalizeCustomerCollection({partyId:"p",accountId:"a",paymentDate:"2026-07-14",paymentMethod:"cash",allocations:[{invoiceId:"i",allocatedAmount:0}]}).error).toContain("sıfırdan");expect(normalizeCustomerCollection({partyId:"p",accountId:"a",paymentDate:"2026-07-14",paymentMethod:"wire" as never,allocations:[{invoiceId:"i",allocatedAmount:1}]}).error).toContain("yöntemi")});
});

describe("deterministic finance calculations",()=>{
  it("derives paid, outstanding and percentage",()=>{expect(invoicePaidAmount(120,80)).toBe(40);expect(invoiceOutstandingAmount(120,40)).toBe(80);expect(invoicePaymentPercentage(120,30)).toBe(25)});
  it("calculates overdue without a stored overdue status",()=>{expect(isInvoiceOverdue(invoice(),new Date("2026-07-14"))).toBe(true);expect(invoiceDaysOverdue(invoice(),new Date("2026-07-14"))).toBe(4);expect(isInvoiceOverdue(invoice({status:"draft"}),new Date("2026-07-14"))).toBe(false)});
  it("assigns every receivable aging bucket",()=>{expect([0,1,31,61,91].map(receivableAgingBucket)).toEqual(["current","1_30","31_60","61_90","90_plus"])});
  it("derives currency-safe schedules and party summaries",()=>{const invoices=[invoice(),invoice({id:"invoice-2",currency:"EUR",outstandingAmount:50,dueDate:"2026-08-01"})];const summary=partyReceivableSummary("party-1",invoices,[payment()],new Date("2026-07-14"));expect(summary).toMatchObject({byCurrency:{TRY:{totalOpenReceivable:100,overdueReceivable:100},EUR:{totalOpenReceivable:50,overdueReceivable:0}},openInvoiceCount:2,lastCollectionDate:"2026-07-12",paymentHistoryCount:1});expect(receivableSchedule(invoices,new Date("2026-07-14"))[0].overdue).toBe(true)});
  it("derives account balance from opening and posted directions",()=>expect(financeAccountBalance(100,[payment({amount:50}),payment({id:"p2",direction:"outflow",amount:20})])).toBe(130));
  it("labels statuses and methods without AI claims",()=>{expect(financeInvoiceStatusLabels.partially_paid).toBe("Kısmen ödendi");expect(financePaymentMethodLabels.bank_transfer).toBe("Banka havalesi");expect(isFinanceInvoiceTerminal("paid")).toBe(true)});
});

describe("finance repository",()=>{
  it("scopes accounts and invoices to company and excludes archives",async()=>{const client=new Client();const repo=createFinanceRepository(client as unknown as FinanceDataClient);await repo.listFinanceAccounts("company-1");await repo.listFinanceInvoices("company-1");for(const x of client.queries){expect(x.query.ops).toContainEqual(["eq","company_id","company-1"]);expect(x.query.ops).toContainEqual(["is","archived_at",null])}});
  it("includes archived records only explicitly",async()=>{const client=new Client();await createFinanceRepository(client as unknown as FinanceDataClient).listFinanceInvoices("company-1",{includeArchived:true});expect(client.queries[0].query.ops).not.toContainEqual(["is","archived_at",null])});
  it("loads linked invoice by exact Sales Order ID",async()=>{const client=new Client([{data:invoiceRow,error:null}]);const result=await createFinanceRepository(client as unknown as FinanceDataClient).getFinanceInvoiceForSalesOrder("company-1","order-1");expect(result.data?.invoiceNumber).toBe("FTR-2026-000001");expect(client.queries[0].query.ops).toContainEqual(["eq","source_sales_order_id","order-1"])});
  it("uses controlled account and invoice RPCs",async()=>{const client=new Client([{data:{id:"account-1",company_id:"company-1",name:"Kasa",account_type:"cash",currency:"TRY",iban:null,opening_balance:0,archived_at:null,created_by:"u",updated_by:"u",created_at:"d",updated_at:"d"},error:null}]);const repo=createFinanceRepository(client as unknown as FinanceDataClient);await repo.createFinanceAccount("company-1",{name:"Kasa",accountType:"cash",currency:"TRY"});await repo.createSalesInvoiceFromSalesOrder("company-1",{salesOrderId:"order-1",dueDate:"2026-07-20"});await repo.transitionFinanceInvoiceStatus("company-1",{invoiceId:"invoice-1",destinationStatus:"issued"});expect(client.rpc.mock.calls.map(x=>x[0])).toEqual(["create_finance_account","create_sales_invoice_from_sales_order","transition_finance_invoice_status"])});
  it("records allocations atomically without totals chosen by UI",async()=>{const client=new Client();const result=await createFinanceRepository(client as unknown as FinanceDataClient).recordCustomerCollection("company-1",{partyId:"party-1",accountId:"account-1",paymentDate:"2026-07-14",paymentMethod:"cash",allocations:[{invoiceId:"invoice-1",allocatedAmount:100}]});expect(result.data?.message).toBe("Tahsilat başarıyla kaydedildi.");const payload=client.rpc.mock.calls[0][1];expect(payload).toHaveProperty("allocations");expect(payload).not.toHaveProperty("payment_amount")});
  it("maps duplicate Sales Orders, IBAN and permissions safely",()=>{expect(mapFinanceError({code:"23505",message:"source_sales_order constraint"}).message).toContain("zaten");expect(mapFinanceError({code:"23505",message:"iban private"}).message).toContain("IBAN");expect(mapFinanceError({code:"42501"}).code).toBe("forbidden")});
});

describe("migration contract",()=>{
  it("creates canonical company-scoped Finance tables",()=>{for(const name of ["finance_accounts","finance_invoices","finance_invoice_items","finance_invoice_status_history","finance_payments","finance_payment_allocations","finance_document_number_counters"])expect(migration).toContain(`create table public.${name}`)});
  it("uses party_id as the stable relationship, not VKN matching",()=>{expect(migration).toContain("party_id uuid not null");expect(migration).toContain("finance_invoices_party_company_fk");expect(migration).not.toMatch(/where .*tax_id.*=.*tax_id/i)});
  it("generates race-safe company/type/year numbers",()=>{expect(migration).toContain("primary key(company_id,document_type,calendar_year)");expect(migration).toContain("on conflict(company_id,document_type,calendar_year) do update");expect(migration).toContain("'FTR-'");expect(migration).toContain("'THS-'")});
  it("locks and accepts only active completed Sales Orders once",()=>{expect(migration).toContain("so.id=target_sales_order_id and so.company_id=target_company_id for update");expect(migration).toContain("Only completed sales orders can be invoiced");expect(migration).toContain("Archived sales order cannot be invoiced");expect(migration).toContain("Cancelled sales order cannot be invoiced");expect(migration).toContain("Sales order already has an invoice")});
  it("copies exact order totals, items and canonical context",()=>{for(const value of ["order_row.party_id","order_row.contact_id","order_row.opportunity_id","order_row.owner_user_id","order_row.subtotal","order_row.discount_total","order_row.tax_total","order_row.other_tax_total","order_row.grand_total"])expect(migration).toContain(value);expect(migration).toContain("oi.ordered_quantity");expect(migration).not.toContain("line_cost")});
  it("captures immutable party and contact identity snapshots",()=>{for(const value of ["party_row.display_name","party_row.tax_id","party_row.tax_office","party_row.address","contact_row.email","contact_row.phone"])expect(migration).toContain(value);expect(migration).toContain("Finance invoice snapshot is immutable")});
  it("creates initial history and controlled invoice transitions",()=>{expect(migration).toContain("null,'draft',actor_id");expect(migration).toContain("when 'draft' then destination_status in ('issued','cancelled')");expect(migration).not.toContain("when 'partially_paid' then");expect(migration).toContain("Invoice with payment allocations cannot be cancelled")});
  it("keeps overdue deterministic and allocation-driven statuses",()=>{expect(migration).not.toMatch(/status.*overdue/);expect(migration).toContain("then 'paid' else 'partially_paid'");expect(migration).toContain("outstanding_amount=outstanding_amount-allocation_amount")});
  it("validates same party, currency, account and outstanding balance",()=>{expect(migration).toContain("Collection invoice must belong to selected party and company");expect(migration).toContain("Collection invoices must use one currency");expect(migration).toContain("Finance account currency must match invoice currency");expect(migration).toContain("Allocation exceeds invoice outstanding amount")});
  it("makes payments and allocations immutable with no reversal",()=>{expect(migration).toContain("finance_payments_immutable");expect(migration).toContain("finance_allocations_immutable");expect(migration).not.toMatch(/reverse_finance|delete from public\.finance_payments/)});
  it("restricts mutation RPCs to operators and tables to member reads",()=>{expect(migration.match(/public\.is_company_operator\(target_company_id\)/g)?.length).toBeGreaterThanOrEqual(6);expect(migration).toContain("grant select on table public.finance_accounts");expect(migration).not.toMatch(/grant (insert|update|delete) on table public\.finance/);expect(migration.match(/enable row level security/g)).toHaveLength(7)});
  it("has no Sales Order, quote, opportunity, legacy ledger or store writes",()=>{expect(migration).not.toMatch(/update public\.(sales_orders|sales_quotes|sales_opportunities)/);expect(migration).not.toMatch(/financeStore|cariStore|ledger|postEntry/)});
});

describe("legacy boundary",()=>{
  it("keeps browser-local stores explicitly unsynchronized",()=>{expect(FINANCE_LEGACY_BOUNDARY).toMatchObject({synchronized:false,ledgerPosting:false});expect(financeStoreSource).not.toContain("financeRepository");expect(cariStoreSource).not.toContain("financeRepository");expect(ledgerBridgeSource).not.toContain("financeRepository")});
});
