import { describe, expect, it } from 'vitest'
import appSource from '../../../../App.tsx?raw'
import salesLayoutSource from '../../ui/SalesLayout.tsx?raw'
import firmDetailSource from '../../ui/FirmDetailPage.tsx?raw'
import pagesSource from './CustomerHealthPages.tsx?raw'
import panelSource from './FirmCustomerHealthPanel.tsx?raw'
import type { BusinessParty } from '../../crm/types'
import type { CustomerHealthAssessment, CustomerHealthCurrencyContext, CustomerHealthEvidence, CustomerHealthFactor } from '../types'
import { batchPartyIds, filterHealthRows, groupEvidence, mergeCustomerHealth, negativeFactors, persistentMethodology, sortHealthRows, sourceRoute } from './customerHealthUIModel'

const party = (id: string, roles: BusinessParty['roles'] = ['customer'], active = true) => ({ id, displayName: id, roles, archivedAt: active ? null : '2026-01-01', relationshipStatus: 'active' } as BusinessParty)
const assessment = (partyId: string, healthStatus: CustomerHealthAssessment['healthStatus'] = 'healthy', id = `a-${partyId}`) => ({ id, partyId, isCurrent: true, healthStatus, evaluatedOn: '2026-07-15', dataSufficiency: 'sufficient', confidence: 'high' } as CustomerHealthAssessment)
const factor = (assessmentId: string, direction: CustomerHealthFactor['direction'] = 'negative', id = `f-${assessmentId}`) => ({ id, assessmentId, direction, factorCode: 'overdue_receivable', severity: 'warning', sourceDomain: 'finance', observedAt: '2026-07-10' } as CustomerHealthFactor)

describe('Customer Health UI V1', () => {
  it('registers protected overview, current and immutable historical routes', () => { expect(appSource).toContain('path="musteri-sagligi"'); expect(appSource).toContain('path="musteri-sagligi/:partyId"'); expect(appSource).toContain('path="musteri-sagligi/:partyId/degerlendirmeler/:assessmentId"') })
  it('places Müşteri Sağlığı in the customer group before the sales-process group', () => { expect(salesLayoutSource.indexOf("'Müşteri Sağlığı'")).toBeLessThan(salesLayoutSource.indexOf("'Potansiyel Müşteriler'")) })
  it('merges canonical active customer parties by party_id and preserves unassessed state', () => { const rows = mergeCustomerHealth([party('one'), party('two'), party('supplier', ['supplier']), party('inactive', ['customer'], false)], [assessment('one')]); expect(rows.map(r => r.party.id)).toEqual(['one', 'two']); expect(rows[1].assessment).toBeNull() })
  it('keeps unassessed separate from insufficient_data', () => { const rows = mergeCustomerHealth([party('one'), party('two')], [assessment('one', 'insufficient_data')]); expect(filterHealthRows(rows, { status: 'unassessed' }).map(r => r.party.id)).toEqual(['two']); expect(filterHealthRows(rows, { status: 'insufficient_data' }).map(r => r.party.id)).toEqual(['one']) })
  it('orders critical, risky, watch, insufficient, unassessed and healthy', () => { const rows = mergeCustomerHealth(['healthy','unassessed','watch','critical','insufficient','risky'].map(id => party(id)), [assessment('healthy','healthy'),assessment('watch','watch'),assessment('critical','critical'),assessment('insufficient','insufficient_data'),assessment('risky','risky')]); expect(sortHealthRows(rows).map(r => r.party.id)).toEqual(['critical','risky','watch','insufficient','unassessed','healthy']) })
  it('filters by name, factor and currency without tax identifiers', () => { const a = assessment('Acme'); const rows = mergeCustomerHealth([party('Acme')],[a],[factor(a.id)],[{ assessmentId:a.id,currency:'TRY' } as CustomerHealthCurrencyContext]); expect(filterHealthRows(rows,{search:'acme',factor:'overdue_receivable',currency:'TRY'})).toHaveLength(1); expect(pagesSource).not.toMatch(/taxId|VKN \/ TCKN/) })
  it('batches more than 200 refresh IDs sequentially', () => { expect(batchPartyIds(Array.from({length:401},(_,i)=>String(i))).map(x=>x.length)).toEqual([200,200,1]); expect(pagesSource).toContain('for (let index = 0; index < batches.length; index++)') })
  it('uses only controlled RPC repository refresh functions and no automatic refresh', () => { expect(pagesSource).toContain('refreshCompanyCustomerHealth'); expect(pagesSource).toContain('refreshCustomerHealthAssessment'); expect(pagesSource).not.toMatch(/\.from\(['"]customer_health/); expect(pagesSource).not.toMatch(/useEffect\([^)]*refreshCustomerHealthAssessment/) })
  it('sorts negative factors before positive presentation and critical first', () => { expect(negativeFactors([factor('a','negative','w'),{...factor('a','negative','c'),severity:'critical'},factor('a','positive','p')]).map(x=>x.id)).toEqual(['c','w']); expect(pagesSource.indexOf('Risk ve dikkat faktörleri')).toBeLessThan(pagesSource.indexOf('Olumlu göstergeler')) })
  it('groups evidence chronologically and links only safe routed types', () => { const rows = [{id:'old',factorId:'f',observedAt:'2026-01-01',createdAt:'2026-01-01'},{id:'new',factorId:'f',observedAt:'2026-02-01',createdAt:'2026-02-01'}] as CustomerHealthEvidence[]; expect(groupEvidence(rows).f.map(x=>x.id)).toEqual(['new','old']); expect(sourceRoute({...rows[0],sourceType:'sales_activity'})).toBeNull(); expect(sourceRoute({...rows[0],sourceType:'finance_invoice',sourceId:'i'})).toBe('/dashboard/finans/faturalar/i') })
  it('contains persistent non-predictive language and no score or monetary-risk claims', () => { expect(persistentMethodology).toContain('Müşteri kaybı olasılığı veya gelir kaybı tahmini değildir.'); expect(pagesSource).not.toMatch(/churn|AI score|0–100|weighted exposure/i) })
  it('keeps currency cards separate and does not aggregate currencies', () => { expect(pagesSource).toContain('contexts.map'); expect(pagesSource).toContain('Para birimleri kur kaynağı olmadan birleştirilmez.'); expect(pagesSource).not.toContain('reduce((sum') })
  it('renders historical banner, current link and no historical refresh control', () => { expect(pagesSource).toContain('Tarihsel değerlendirme'); expect(pagesSource).toContain('Güncel değerlendirmeyi aç'); expect(pagesSource).toContain("const writable = canRefresh(activeCompany?.role) && !assessmentId") })
  it('adds Firma context by party id without legacy Cari or Firma 360 claims', () => { expect(firmDetailSource).toContain('FirmCustomerHealthPanel'); expect(panelSource).toContain('party.id'); expect(panelSource).not.toMatch(/cariStore|Firma 360/) })
  it('does not add scoring, forecasting, analytics, task or attention integrations', () => { expect(salesLayoutSource).not.toMatch(/Fırsat Skoru|Forecast|Analitik/); expect(pagesSource).not.toMatch(/createSalesActivity|createSalesTask|AttentionQueue|Yapılacaklar/) })
})
