import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { ArrowLeft, History, RefreshCw, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useCompanies } from '../../../../company/companyContext'
import Modal from '../../../../surfaces/dashboard/components/Modal'
import { getBusinessParty, listBusinessParties } from '../../crm/crmRepository'
import type { BusinessParty } from '../../crm/types'
import { Badge, PageState, buttonPrimary, buttonSecondary, inputClass } from '../../ui/CRMUI'
import { getCurrentCustomerHealthForParty, getCustomerHealthAssessment, getCustomerHealthCompanySummary, listCurrentCustomerHealth, listCustomerHealthCurrencyContexts, listCustomerHealthEvidence, listCustomerHealthFactors, listCustomerHealthHistory, refreshCompanyCustomerHealth, refreshCustomerHealthAssessment } from '../customerHealthRepository'
import { confidenceLabels, factorSeverityLabels, formatCurrencyFactor, healthLabels, selectPrimaryRisk, sufficiencyLabels } from '../customerHealthViewModel'
import type { CustomerHealthAssessment, CustomerHealthCurrencyContext, CustomerHealthEvidence, CustomerHealthFactor, CustomerHealthFactorCode, CustomerHealthSummary, CustomerHealthStatus } from '../types'
import { batchPartyIds, domainLabels, factorLabels, filterHealthRows, groupEvidence, isEvaluatedToday, mergeCustomerHealth, negativeFactors, persistentMethodology, positiveFactors, sortHealthRows, sourceLabels, sourceRoute, type HealthFilters } from './customerHealthUIModel'

const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium' }).format(new Date(value)) : '—'
const number = (value: number) => new Intl.NumberFormat('tr-TR').format(value)
const canRefresh = (role: string | null | undefined) => role === 'owner' || role === 'employee'
const riskCodes: CustomerHealthFactorCode[] = ['overdue_receivable', 'late_payment_pattern', 'order_inactivity', 'order_value_decline', 'quote_outcome_deterioration', 'relationship_inactivity']

function Methodology() { return <aside className="rounded-lg border border-line bg-paper px-4 py-3 text-sm text-ink-soft"><ShieldCheck size={16} className="mr-2 inline text-crimson" />{persistentMethodology}</aside> }
function Notice({ children, error = false }: { children: ReactNode; error?: boolean }) { return <div role={error ? 'alert' : 'status'} className={`rounded-lg border px-4 py-3 text-sm ${error ? 'border-crimson/25 bg-crimson/5 text-crimson' : 'border-emerald-600/20 bg-emerald-600/10 text-emerald-800'}`}>{children}</div> }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-card border border-line bg-surface p-4"><p className="text-xs font-medium uppercase tracking-wide text-ink-mute">{label}</p><p className="mt-2 font-mono text-2xl text-ink">{value}</p></div> }
function HealthBadge({ status }: { status: CustomerHealthStatus }) { return <Badge>{healthLabels[status]}</Badge> }

export function CustomerHealthOverviewPage() {
  const { activeCompany } = useCompanies(); const writable = canRefresh(activeCompany?.role)
  const [parties, setParties] = useState<BusinessParty[]>([]); const [assessments, setAssessments] = useState<CustomerHealthAssessment[]>([]); const [factors, setFactors] = useState<CustomerHealthFactor[]>([]); const [contexts, setContexts] = useState<CustomerHealthCurrencyContext[]>([]); const [summary, setSummary] = useState<CustomerHealthSummary | null>(null)
  const requestId = useRef(0)
  const [state, setState] = useState<'loading'|'error'|'ready'>('loading'); const [filters, setFilters] = useState<HealthFilters>({}); const [sort, setSort] = useState<'health'|'name'|'oldest'|'newest'>('health'); const [refreshOpen, setRefreshOpen] = useState(false); const [refreshing, setRefreshing] = useState(false); const [progress, setProgress] = useState(''); const [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null)
  const load = useCallback(async () => {
    if (!activeCompany) return; const request = ++requestId.current; setState('loading')
    const [partyResult, assessmentResult, summaryResult] = await Promise.all([listBusinessParties(activeCompany.id), listCurrentCustomerHealth(activeCompany.id), getCustomerHealthCompanySummary(activeCompany.id)])
    if (request !== requestId.current) return; if (partyResult.error || assessmentResult.error || summaryResult.error) return setState('error')
    const [factorResults, contextResults] = await Promise.all([
      Promise.all(assessmentResult.data.map(row => listCustomerHealthFactors(activeCompany.id, row.id))),
      Promise.all(assessmentResult.data.map(row => listCustomerHealthCurrencyContexts(activeCompany.id, row.id))),
    ])
    if (request !== requestId.current) return; if ([...factorResults, ...contextResults].some(result => result.error)) return setState('error')
    setParties(partyResult.data); setAssessments(assessmentResult.data); setSummary(summaryResult.data); setFactors(factorResults.flatMap(result => result.data ?? [])); setContexts(contextResults.flatMap(result => result.data ?? [])); setState('ready')
  }, [activeCompany])
  // The effect synchronizes the page with the selected remote company.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); return () => { requestId.current += 1 } }, [load])
  const rows = useMemo(() => mergeCustomerHealth(parties, assessments, factors, contexts), [parties, assessments, factors, contexts])
  const visible = useMemo(() => sortHealthRows(filterHealthRows(rows, filters), sort), [rows, filters, sort])
  const latest = assessments.map(row => row.evaluatedOn).sort().at(-1) ?? null
  const refreshAll = async () => {
    if (!activeCompany) return; setRefreshing(true); setNotice(null)
    const batches = batchPartyIds(rows.map(row => row.party.id)); let evaluated = 0, created = 0, unchanged = 0, failed = 0
    for (let index = 0; index < batches.length; index++) {
      setProgress(`${index + 1}/${batches.length}`); const result = await refreshCompanyCustomerHealth(activeCompany.id, { partyIds: batches[index], limit: batches[index].length })
      if (result.error) { setRefreshing(false); setNotice({ text: result.error.message, error: true }); return }
      evaluated += result.data.evaluatedCount; created += result.data.createdCount; unchanged += result.data.unchangedCount; failed += result.data.failedCount
    }
    setRefreshing(false); setRefreshOpen(false); setProgress(''); setNotice({ text: failed ? `Değerlendirme kısmen tamamlandı. Başarısız kayıtlar güvenli hata kodlarıyla raporlandı. Değerlendirilen: ${evaluated}, yeni: ${created}, değişmeyen: ${unchanged}, başarısız: ${failed}.` : `Müşteri Sağlığı değerlendirmeleri yenilendi. Değerlendirilen: ${evaluated}, yeni: ${created}, değişmeyen: ${unchanged}, başarısız: 0.` }); await load()
  }
  if (state === 'loading') return <main className="mx-auto max-w-7xl px-4 py-8 md:px-8"><PageState kind="loading" message="Müşteri Sağlığı yükleniyor…" /></main>
  if (state === 'error') return <main className="mx-auto max-w-7xl px-4 py-8 md:px-8"><PageState kind="error" message="Müşteri Sağlığı verileri yüklenemedi." retry={() => void load()} /></main>
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 md:px-8 md:py-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-serif text-3xl text-ink">Müşteri Sağlığı ve Gelir Riski</h1><p className="mt-2 text-sm text-ink-soft">Son değerlendirme: {date(latest)}</p></div>{writable ? <button type="button" className={buttonPrimary} onClick={() => setRefreshOpen(true)}><RefreshCw size={16} className="mr-2 inline" />Değerlendirmeleri yenile</button> : <p className="rounded-lg border border-line px-3 py-2 text-sm text-ink-mute">Salt okunur: değerlendirmeleri yalnız owner veya employee yenileyebilir.</p>}</header>
    <Methodology />{notice && <Notice error={notice.error}>{notice.text}</Notice>}
    <section aria-label="Şirket Müşteri Sağlığı özeti" className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><Stat label="Kritik" value={summary?.criticalCount ?? 0}/><Stat label="Riskli" value={summary?.riskyCount ?? 0}/><Stat label="İzlenmeli" value={summary?.watchCount ?? 0}/><Stat label="Sağlıklı" value={summary?.healthyCount ?? 0}/><Stat label="Yetersiz veri" value={summary?.insufficientDataCount ?? 0}/><Stat label="Bugün yenilenmemiş" value={summary?.assessmentsRequiringRefresh ?? 0}/></section>
    {rows.length === 0 ? <PageState kind="empty" message="Etkin müşteri rolüne sahip Firma bulunmuyor." /> : <>
      <section className="rounded-card border border-line bg-surface p-5"><h2 className="font-serif text-xl">Öne çıkan risk sinyalleri</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{riskCodes.map(code => <button type="button" key={code} onClick={() => setFilters(current => ({ ...current, factor: code }))} className="focus-ring rounded-lg border border-line p-4 text-left hover:border-crimson/30"><span className="text-sm font-medium">{factorLabels[code]}</span><span className="mt-1 block text-xs text-ink-mute">{summary?.negativeFactorDistribution[code] ?? 0} güncel müşteri</span></button>)}</div></section>
      <section className="rounded-card border border-line bg-surface p-5"><div className="flex flex-wrap items-end gap-3"><label className="min-w-[210px] flex-1 text-sm">Firma ara<input className={`${inputClass} mt-1`} value={filters.search ?? ''} onChange={e => setFilters({ ...filters, search: e.target.value })}/></label><label className="text-sm">Sağlık durumu<select className={`${inputClass} mt-1`} value={filters.status ?? ''} onChange={e => setFilters({ ...filters, status: e.target.value as HealthFilters['status'] })}><option value="">Tümü</option><option value="critical">Kritik</option><option value="risky">Riskli</option><option value="watch">İzlenmeli</option><option value="insufficient_data">Yetersiz veri</option><option value="unassessed">Henüz değerlendirilmedi</option><option value="healthy">Sağlıklı</option></select></label><label className="text-sm">Veri yeterliliği<select className={`${inputClass} mt-1`} value={filters.sufficiency ?? ''} onChange={e => setFilters({ ...filters, sufficiency: e.target.value })}><option value="">Tümü</option><option value="sufficient">Yeterli</option><option value="partial">Kısmi</option><option value="insufficient">Yetersiz</option></select></label><label className="text-sm">Güven<select className={`${inputClass} mt-1`} value={filters.confidence ?? ''} onChange={e => setFilters({ ...filters, confidence: e.target.value })}><option value="">Tümü</option><option value="high">Yüksek</option><option value="medium">Orta</option><option value="low">Düşük</option></select></label><label className="text-sm">Yenilenme<select className={`${inputClass} mt-1`} value={filters.today ?? ''} onChange={e => setFilters({ ...filters, today: e.target.value as HealthFilters['today'] })}><option value="">Tümü</option><option value="today">Bugün yenilendi</option><option value="not_today">Bugün yenilenmedi</option></select></label><label className="text-sm">Para birimi<select className={`${inputClass} mt-1`} value={filters.currency ?? ''} onChange={e => setFilters({ ...filters, currency: e.target.value })}><option value="">Tümü</option>{['TRY','EUR','USD','GBP'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Sıralama<select className={`${inputClass} mt-1`} value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="health">Sağlık önceliği</option><option value="name">Firma adı</option><option value="oldest">En eski değerlendirme</option><option value="newest">En yeni değerlendirme</option></select></label><button type="button" className={buttonSecondary} onClick={() => setFilters({})}>Filtreleri temizle</button></div></section>
      {assessments.length === 0 && <Notice>Firmalar mevcut ancak henüz hiçbir Müşteri Sağlığı değerlendirmesi oluşturulmadı.</Notice>}
      {visible.length === 0 ? <PageState kind="empty" message="Filtrelerle eşleşen müşteri bulunamadı." /> : <section className="grid gap-3 md:grid-cols-2">{visible.map(row => { const negative = negativeFactors(row.factors); const positive = positiveFactors(row.factors); const primary = selectPrimaryRisk(row.factors); return <Link key={row.party.id} to={`/dashboard/satis/musteri-sagligi/${row.party.id}`} className="focus-ring rounded-card border border-line bg-surface p-5 hover:border-crimson/30"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-medium text-ink">{row.party.displayName}</h2>{row.assessment ? <HealthBadge status={row.assessment.healthStatus}/> : <Badge muted>Henüz değerlendirilmedi</Badge>}</div>{row.assessment ? <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-ink-mute">Öncelikli risk</dt><dd>{primary ? factorLabels[primary.factorCode] : 'Olumsuz faktör oluşmadı'}</dd></div><div><dt className="text-ink-mute">Yeterlilik / güven</dt><dd>{sufficiencyLabels[row.assessment.dataSufficiency]} · {confidenceLabels[row.assessment.confidence]}</dd></div><div><dt className="text-ink-mute">Değerlendirme</dt><dd>{date(row.assessment.evaluatedOn)} · {isEvaluatedToday(row.assessment) ? 'Bugün yenilendi' : 'Bugün yenilenmedi'}</dd></div><div><dt className="text-ink-mute">Faktörler / para birimleri</dt><dd>{negative.length} olumsuz · {positive.length} olumlu · {row.contexts.map(c => c.currency).join(', ') || 'Bağlam yok'}</dd></div></dl> : <p className="mt-3 text-sm text-ink-soft">Bu Firma için henüz değerlendirme snapshot’ı yoktur.</p>}</Link>})}</section>}
      <section className="rounded-card border border-line bg-surface p-5"><h2 className="font-serif text-xl">Gelir riski sinyalleri</h2><p className="mt-1 text-sm text-ink-mute">Yalnız açıklanabilir güncel faktörler gösterilir; öngörülen kayıp veya risk altındaki gelir hesaplanmaz.</p><div className="mt-4 space-y-2">{rows.flatMap(row => negativeFactors(row.factors).filter(f => riskCodes.includes(f.factorCode)).map(f => ({ row, f }))).map(({ row, f }) => <Link key={f.id} to={`/dashboard/satis/musteri-sagligi/${row.party.id}`} className="block rounded-lg border border-line p-3 text-sm"><strong>{row.party.displayName}</strong> · {healthLabels[row.assessment!.healthStatus]} · {factorLabels[f.factorCode]} · {factorSeverityLabels[f.severity]}{f.currency ? ` · ${f.currency}` : ''}<span className="mt-1 block text-xs text-ink-mute">{f.explanation} · {date(f.observedAt)}</span></Link>)}</div></section>
    </>}
    {refreshOpen && <Modal title="Değerlendirmeleri yenile" onClose={() => !refreshing && setRefreshOpen(false)}><p className="text-sm text-ink-soft">Değerlendirmeler mevcut yapılandırılmış kayıtlardan yeniden hesaplanır. Değişmeyen kaynak fingerprint’i mevcut snapshot’ı korur; değişen kayıtlar yeni ve değiştirilemez bir snapshot oluşturur. CRM, Satış ve Finans kaynakları değiştirilmez; görev veya mesaj oluşturulmaz.</p>{refreshing && <p role="status" className="mt-3 text-sm">İşleniyor: {progress}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className={buttonSecondary} onClick={() => setRefreshOpen(false)}>Vazgeç</button><button type="button" disabled={refreshing} className={buttonPrimary} onClick={() => void refreshAll()}>{refreshing ? 'Yenileniyor…' : 'Yenile'}</button></div></Modal>}
  </main>
}

function EvidenceList({ factor, evidence }: { factor: CustomerHealthFactor; evidence: CustomerHealthEvidence[] }) { const rows = groupEvidence(evidence)[factor.id] ?? []; return <details className="mt-4"><summary className="focus-ring cursor-pointer text-sm font-medium text-crimson">Kanıtlar ({rows.length})</summary><div className="mt-3 space-y-2">{rows.map(row => { const route = sourceRoute(row); const content = <><strong>{sourceLabels[row.sourceType]}</strong> · {row.label}<span className="block text-xs text-ink-mute">{date(row.observedAt)}{row.amount !== null ? ` · ${formatCurrencyFactor(row.amount, row.currency)}` : ''}</span></>; return route ? <Link key={row.id} to={route} className="block rounded-lg border border-line p-3 text-sm hover:border-crimson/30">{content}</Link> : <div key={row.id} className="rounded-lg border border-line p-3 text-sm">{content}</div> })}</div></details> }
function FactorCard({ factor, evidence }: { factor: CustomerHealthFactor; evidence: CustomerHealthEvidence[] }) { const fields = [['Gözlem', date(factor.observedAt)], ['Dönem', factor.periodStart || factor.periodEnd ? `${date(factor.periodStart)} – ${date(factor.periodEnd)}` : null], ['Metrik', factor.metricValue], ['Baz', factor.baselineValue], ['Eşik', factor.thresholdValue], ['Değişim', factor.deltaPct === null ? null : `%${number(factor.deltaPct)}`], ['Tutar', factor.amount === null ? null : formatCurrencyFactor(factor.amount, factor.currency)]]; return <article className="rounded-lg border border-line p-4"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{factorLabels[factor.factorCode]}</h3><Badge>{factorSeverityLabels[factor.severity]}</Badge><Badge muted>{domainLabels[factor.sourceDomain]}</Badge></div><p className="mt-3 text-sm text-ink-soft">{factor.explanation}</p>{factor.recommendation && <p className="mt-2 text-sm"><strong>Öneri:</strong> {factor.recommendation}</p>}<dl className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4">{fields.filter(([, value]) => value !== null).map(([label, value]) => <div key={String(label)}><dt className="text-ink-mute">{label}</dt><dd>{String(value)}</dd></div>)}<div><dt className="text-ink-mute">Kanıt sayısı</dt><dd>{factor.evidenceCount}</dd></div></dl><EvidenceList factor={factor} evidence={evidence}/></article> }

export function CustomerHealthDetailPage() {
  const { activeCompany } = useCompanies(); const { partyId = '', assessmentId } = useParams(); const writable = canRefresh(activeCompany?.role) && !assessmentId
  const requestId = useRef(0)
  const [party, setParty] = useState<BusinessParty | null>(null); const [assessment, setAssessment] = useState<CustomerHealthAssessment | null>(null); const [factors, setFactors] = useState<CustomerHealthFactor[]>([]); const [evidence, setEvidence] = useState<CustomerHealthEvidence[]>([]); const [contexts, setContexts] = useState<CustomerHealthCurrencyContext[]>([]); const [history, setHistory] = useState<CustomerHealthAssessment[]>([]); const [state, setState] = useState<'loading'|'error'|'not-found'|'ready'>('loading'); const [confirm, setConfirm] = useState(false); const [refreshing, setRefreshing] = useState(false); const [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null)
  const load = useCallback(async () => {
    if (!activeCompany) return; const request = ++requestId.current; setState('loading')
    const [partyResult, assessmentResult, historyResult] = await Promise.all([getBusinessParty(activeCompany.id, partyId, true), assessmentId ? getCustomerHealthAssessment(activeCompany.id, assessmentId) : getCurrentCustomerHealthForParty(activeCompany.id, partyId), listCustomerHealthHistory(activeCompany.id, partyId)])
    if (request !== requestId.current) return; if (partyResult.error?.code === 'not_found' || assessmentResult.error?.code === 'not_found') return setState('not-found'); if (partyResult.error || assessmentResult.error || historyResult.error) return setState('error')
    if (assessmentResult.data && assessmentResult.data.partyId !== partyId) return setState('not-found')
    setParty(partyResult.data); setAssessment(assessmentResult.data); setHistory(historyResult.data)
    if (!assessmentResult.data) { setFactors([]); setEvidence([]); setContexts([]); return setState('ready') }
    const [factorResult, evidenceResult, contextResult] = await Promise.all([listCustomerHealthFactors(activeCompany.id, assessmentResult.data.id), listCustomerHealthEvidence(activeCompany.id, assessmentResult.data.id), listCustomerHealthCurrencyContexts(activeCompany.id, assessmentResult.data.id)])
    if (request !== requestId.current) return; if (factorResult.error || evidenceResult.error || contextResult.error) return setState('error'); setFactors(factorResult.data); setEvidence(evidenceResult.data); setContexts(contextResult.data); setState('ready')
  }, [activeCompany, partyId, assessmentId])
  // The effect synchronizes the route with the selected immutable snapshot.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); return () => { requestId.current += 1 } }, [load])
  const refresh = async () => { if (!activeCompany) return; setRefreshing(true); const result = await refreshCustomerHealthAssessment(activeCompany.id, { partyId }); setRefreshing(false); if (result.error) return setNotice({ text: result.error.message, error: true }); setConfirm(false); setNotice({ text: result.data.createdNew ? 'Yeni Müşteri Sağlığı değerlendirmesi oluşturuldu.' : 'Kaynak veriler değişmedi. Mevcut değerlendirme korundu.' }); await load() }
  if (state === 'loading') return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="loading" message="Müşteri Sağlığı değerlendirmesi yükleniyor…" /></main>
  if (state === 'error') return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="error" message="Değerlendirme yüklenemedi." retry={() => void load()} /></main>
  if (state === 'not-found' || !party) return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="empty" message="Firma veya değerlendirme bulunamadı ya da bu şirkette görüntülenemiyor." /></main>
  const negative = negativeFactors(factors), positive = positiveFactors(factors), neutral = factors.filter(f => f.direction === 'neutral'), primary = selectPrimaryRisk(factors)
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 md:px-8 md:py-8">
    <Link to="/dashboard/satis/musteri-sagligi" className="text-sm text-crimson"><ArrowLeft size={15} className="mr-1 inline" />Müşteri Sağlığına dön</Link>{assessmentId && <Notice><History size={15} className="mr-2 inline" />Tarihsel değerlendirme — bu değiştirilemez snapshot güncel kaynaklardan yeniden hesaplanmaz.</Notice>}{notice && <Notice error={notice.error}>{notice.text}</Notice>}
    <header className="rounded-card border border-line bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-serif text-3xl">{party.displayName}</h1><Link className="mt-2 inline-block text-sm text-crimson" to={`/dashboard/satis/firmalar/${party.id}`}>Firma Detayına git</Link></div>{assessment && writable && <button type="button" className={buttonPrimary} onClick={() => setConfirm(true)}><RefreshCw size={15} className="mr-2 inline" />Değerlendirmeyi yenile</button>}</div>{assessment ? <><div className="mt-5 flex flex-wrap gap-2"><HealthBadge status={assessment.healthStatus}/><Badge muted>Güven: {confidenceLabels[assessment.confidence]}</Badge><Badge muted>Veri: {sufficiencyLabels[assessment.dataSufficiency]}</Badge></div><p className="mt-4 text-sm text-ink-soft">{assessment.summary}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-ink-mute">Değerlendirme</dt><dd>{date(assessment.evaluatedOn)} · {isEvaluatedToday(assessment) ? 'Bugün yenilendi' : 'Bugün yenilenmedi'}</dd></div><div><dt className="text-ink-mute">Ruleset</dt><dd>{assessment.rulesetVersion}</dd></div>{assessmentId && <div><dt className="text-ink-mute">Yerine yenisi oluşturuldu</dt><dd>{date(assessment.supersededAt)}</dd></div>}</dl></> : <div className="mt-5"><Badge muted>Henüz değerlendirilmedi</Badge><p className="mt-3 text-sm text-ink-soft">Bu Firma için henüz Müşteri Sağlığı snapshot’ı oluşturulmadı.</p>{writable ? <button type="button" className={`${buttonPrimary} mt-4`} onClick={() => setConfirm(true)}>Şimdi değerlendir</button> : <p className="mt-3 text-sm text-ink-mute">Salt okunur erişiminiz nedeniyle değerlendirme başlatamazsınız.</p>}</div>}</header>
    <Methodology /><p className="rounded-lg bg-paper p-3 text-sm text-ink-soft">Güven düzeyi, kanıt kalitesini ifade eder; müşterinin ayrılma olasılığını ifade etmez.</p>
    {assessment && <>{primary ? <section className="rounded-card border border-crimson/25 bg-crimson/5 p-5"><h2 className="font-serif text-xl">Öncelikli risk sinyali</h2><div className="mt-4"><FactorCard factor={primary} evidence={evidence}/></div></section> : <Notice>Bu değerlendirmede uyarı veya kritik düzeyde olumsuz faktör oluşmadı.</Notice>}{assessment.dataSufficiency !== 'sufficient' && <Notice>Kanıt geçmişi {sufficiencyLabels[assessment.dataSufficiency].toLocaleLowerCase('tr-TR')} olduğu için sonuç kesin müşteri sağlığı garantisi değildir.</Notice>}
      <section className="space-y-3"><h2 className="font-serif text-xl">Risk ve dikkat faktörleri</h2>{negative.length ? negative.map(f => <FactorCard key={f.id} factor={f} evidence={evidence}/>) : <p className="text-sm text-ink-mute">Olumsuz faktör oluşmadı.</p>}</section>
      {positive.length > 0 && <section className="space-y-3"><h2 className="font-serif text-xl">Olumlu göstergeler</h2>{positive.map(f => <FactorCard key={f.id} factor={f} evidence={evidence}/>)}</section>}{neutral.length > 0 && <section className="space-y-3"><h2 className="font-serif text-xl">Nötr bağlam</h2>{neutral.map(f => <FactorCard key={f.id} factor={f} evidence={evidence}/>)}</section>}
      <section className="rounded-card border border-line bg-surface p-5"><h2 className="font-serif text-xl">Para birimi bazında ticari bağlam</h2><p className="mt-2 text-sm text-ink-mute">Para birimleri kur kaynağı olmadan birleştirilmez.</p>{contexts.length ? <div className="mt-4 grid gap-4 lg:grid-cols-2">{contexts.map(c => <article key={c.id} className="rounded-lg border border-line p-4"><h3 className="font-mono text-lg">{c.currency}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm">{[['12 ay sipariş', `${c.completedOrderCount12m} · ${formatCurrencyFactor(c.completedOrderValue12m,c.currency)}`],['Son 90 gün', `${c.recentOrderCount90d} · ${formatCurrencyFactor(c.recentOrderValue90d,c.currency)}`],['Önceki 90 gün', `${c.previousOrderCount90d} · ${formatCurrencyFactor(c.previousOrderValue90d,c.currency)}`],['Açık alacak',formatCurrencyFactor(c.openReceivable,c.currency)],['Vadesi geçmiş alacak',formatCurrencyFactor(c.overdueReceivable,c.currency)],['180 gün teklif',`${c.recentQuoteCount180d} · ${formatCurrencyFactor(c.recentQuoteValue180d,c.currency)}`],['Kabul / ret / süre dolma',`${c.acceptedQuoteCount180d} / ${c.rejectedQuoteCount180d} / ${c.expiredQuoteCount180d}`]].map(([label,value])=><div key={label}><dt className="text-ink-mute">{label}</dt><dd>{value}</dd></div>)}</dl></article>)}</div> : <p className="mt-4 text-sm text-ink-mute">Bu snapshot için para birimi bağlamı bulunmuyor.</p>}</section>
    </>}
    <section className="rounded-card border border-line bg-surface p-5"><h2 className="font-serif text-xl">Değerlendirme geçmişi</h2>{history.length ? <div className="mt-4 space-y-2">{history.map(row => <Link key={row.id} to={row.isCurrent ? `/dashboard/satis/musteri-sagligi/${party.id}` : `/dashboard/satis/musteri-sagligi/${party.id}/degerlendirmeler/${row.id}`} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-line p-3 text-sm"><span>{date(row.evaluatedAt)} · {healthLabels[row.healthStatus]} · {confidenceLabels[row.confidence]} · {sufficiencyLabels[row.dataSufficiency]}</span><span className="text-ink-mute">{row.rulesetVersion} · {row.isCurrent ? 'Güncel' : 'Tarihsel'}</span></Link>)}</div> : <p className="mt-3 text-sm text-ink-mute">Değerlendirme geçmişi bulunmuyor.</p>}</section>
    {assessmentId && <Link className={buttonSecondary} to={`/dashboard/satis/musteri-sagligi/${party.id}`}>Güncel değerlendirmeyi aç</Link>}
    {confirm && <Modal title="Müşteri Sağlığını yenile" onClose={() => !refreshing && setConfirm(false)}><p className="text-sm text-ink-soft">Değerlendirme gözlemseldir; kaynak kayıtları değiştirmez. Değişmeyen girdiler mevcut snapshot’ı yeniden kullanır, değişen girdiler yeni bir tarihsel snapshot oluşturur. Görev, aktivite, fırsat veya mesaj oluşturulmaz.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={buttonSecondary} onClick={() => setConfirm(false)}>Vazgeç</button><button type="button" disabled={refreshing} className={buttonPrimary} onClick={() => void refresh()}>{refreshing ? 'Değerlendiriliyor…' : 'Değerlendir'}</button></div></Modal>}
  </main>
}
