import {supabase} from "../../../lib/supabase";
import type {CoverEmailDraft,ExecutionArtifact,ExecutionAssumption,ExecutionCase,ExecutionCaseBundle,ExecutionDecision,ExecutionEvent,ExecutionFieldEdit,ExecutionMissingInput,ExecutionOutcome,ExecutionRepositoryError,ExecutionRepositoryResult,ExecutionResult,InternalReviewSummary,PrepareQuoteCaseInput,PreparedQuoteDraft,ExecutionEvidence,ExecutionEditCategory} from "./types";

interface Response{data:unknown;error:unknown|null}
interface Query extends PromiseLike<Response>{select(value:string):Query;eq(column:string,value:unknown):Query;is(column:string,value:null):Query;order(column:string,options?:{ascending?:boolean}):Query;maybeSingle():PromiseLike<Response>}
interface Table{select(value:string):Query}
export interface AssistedExecutionDataClient{from(table:string):Table;rpc(name:string,args:Record<string,unknown>):PromiseLike<Response>}
const obj=(value:unknown):Record<string,unknown>=>typeof value==="object"&&value!==null?value as Record<string,unknown>:{};
const str=(value:unknown)=>value==null?null:String(value);const num=(value:unknown)=>value==null?null:Number(value);
const caseRow=(value:unknown):ExecutionCase=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseType:r.case_type as ExecutionCase["caseType"],status:r.status as ExecutionCase["status"],targetPartyId:String(r.target_party_id),targetContactId:str(r.target_contact_id),targetOpportunityId:str(r.target_opportunity_id),targetQuoteId:str(r.target_quote_id),executedQuoteId:str(r.executed_quote_id),responsibleUserId:String(r.responsible_user_id),triggerType:r.trigger_type as ExecutionCase["triggerType"],triggeredAt:String(r.triggered_at),preparedAt:str(r.prepared_at),reviewDueAt:str(r.review_due_at),approvedAt:str(r.approved_at),executedAt:str(r.executed_at),completedAt:str(r.completed_at),rulesetKey:r.ruleset_key as ExecutionCase["rulesetKey"],rulesetVersion:String(r.ruleset_version),evidenceQuality:r.evidence_quality as ExecutionCase["evidenceQuality"],summary:String(r.summary),primaryRecommendation:String(r.primary_recommendation),sourceFingerprint:String(r.source_fingerprint),replacesCaseId:str(r.replaces_case_id),createdBy:String(r.created_by),createdAt:String(r.created_at),updatedAt:String(r.updated_at),archivedAt:str(r.archived_at)}};
const evidenceRow=(value:unknown):ExecutionEvidence=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),evidenceType:String(r.evidence_type),sourceDomain:r.source_domain as ExecutionEvidence["sourceDomain"],sourceType:String(r.source_type),sourceRecordId:str(r.source_record_id),observedAt:str(r.observed_at),label:String(r.label),safeSummary:String(r.safe_summary),currency:r.currency as ExecutionEvidence["currency"],amount:num(r.amount),metadata:obj(r.metadata),createdAt:String(r.created_at)}};
const assumptionRow=(value:unknown):ExecutionAssumption=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),assumptionKey:String(r.assumption_key),label:String(r.label),value:r.value,source:r.source as ExecutionAssumption["source"],confidence:r.confidence as ExecutionAssumption["confidence"],requiresConfirmation:Boolean(r.requires_confirmation),confirmedBy:str(r.confirmed_by),confirmedAt:str(r.confirmed_at),createdAt:String(r.created_at)}};
const missingRow=(value:unknown):ExecutionMissingInput=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),inputKey:String(r.input_key),label:String(r.label),severity:r.severity as ExecutionMissingInput["severity"],blocking:Boolean(r.blocking),resolutionType:r.resolution_type as ExecutionMissingInput["resolutionType"],resolvedValue:r.resolved_value,resolvedBy:str(r.resolved_by),resolvedAt:str(r.resolved_at),createdAt:String(r.created_at)}};
const artifactRow=<T=unknown>(value:unknown):ExecutionArtifact<T>=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),artifactType:r.artifact_type as ExecutionArtifact["artifactType"],versionNumber:Number(r.version_number),content:r.content as T,sourceFingerprint:String(r.source_fingerprint),preparedBy:String(r.prepared_by),createdAt:String(r.created_at),supersededAt:str(r.superseded_at)}};
const decisionRow=(value:unknown):ExecutionDecision=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),decision:r.decision as ExecutionDecision["decision"],reasonCode:str(r.reason_code),reasonText:str(r.reason_text),decisionSnapshot:obj(r.decision_snapshot),decidedBy:String(r.decided_by),decidedAt:String(r.decided_at)}};
const editRow=(value:unknown):ExecutionFieldEdit=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),artifactId:String(r.artifact_id),fieldPath:String(r.field_path),originalValue:r.original_value,finalValue:r.final_value,editCategory:r.edit_category as ExecutionFieldEdit["editCategory"],editedBy:String(r.edited_by),editedAt:String(r.edited_at)}};
const eventRow=(value:unknown):ExecutionEvent=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),eventType:String(r.event_type),actorType:r.actor_type as ExecutionEvent["actorType"],actorUserId:str(r.actor_user_id),payload:obj(r.payload),occurredAt:String(r.occurred_at)}};
const outcomeRow=(value:unknown):ExecutionOutcome=>{const r=obj(value);return{id:String(r.id),companyId:String(r.company_id),caseId:String(r.case_id),outcomeType:String(r.outcome_type),sourceDomain:r.source_domain as ExecutionOutcome["sourceDomain"],sourceRecordId:String(r.source_record_id),observedAt:String(r.observed_at),outcomeValue:num(r.outcome_value),currency:r.currency as ExecutionOutcome["currency"],classification:str(r.classification),conclusive:Boolean(r.conclusive),notes:str(r.notes),createdAt:String(r.created_at)}};

export function mapExecutionError(error:unknown):ExecutionRepositoryError{const r=obj(error),code=String(r.code??"");if(code==="42501"||code==="PGRST301")return{code:"forbidden",message:"Bu hazırlanmış iş için değişiklik yetkiniz bulunmuyor.",cause:error};if(code==="PGRST116"||code==="P0002")return{code:"not_found",message:"Hazırlanmış iş bulunamadı.",cause:error};if(["23505","23514","22023"].includes(code))return{code:"conflict",message:"İşlem, eksik bilgiler veya mevcut iş durumu nedeniyle tamamlanamadı.",cause:error};return{code:"database",message:"Hazırlanmış iş işlemi tamamlanamadı. Lütfen yeniden deneyin.",cause:error}}
const invalid=<T>(message:string):ExecutionRepositoryResult<T>=>({data:null,error:{code:"validation",message,cause:null}});

export function createAssistedExecutionRepository(client:AssistedExecutionDataClient){
  async function list<T>(table:string,companyId:string,mapper:(value:unknown)=>T,caseId?:string):Promise<ExecutionRepositoryResult<T[]>>{let query=client.from(table).select("*").eq("company_id",companyId);if(caseId)query=query.eq("case_id",caseId);const orderColumn=table==="execution_cases"?"updated_at":table==="execution_events"?"occurred_at":table==="execution_decisions"?"decided_at":table==="execution_field_edits"?"edited_at":"created_at";const{data,error}=await query.order(orderColumn,{ascending:table!=="execution_cases"&&table!=="execution_events"});return error?{data:null,error:mapExecutionError(error)}:{data:(Array.isArray(data)?data:[]).map(mapper),error:null}}
  const repo={
    async listCases(companyId:string):Promise<ExecutionRepositoryResult<ExecutionCase[]>>{return list("execution_cases",companyId,caseRow)},
    async listPreparedWork(companyId:string){const result=await repo.listCases(companyId);return result.error?result:{data:result.data.filter(row=>!row.archivedAt&&["prepared","awaiting_review","failed"].includes(row.status)),error:null}},
    async getCase(companyId:string,caseId:string):Promise<ExecutionRepositoryResult<ExecutionCase>>{const{data,error}=await client.from("execution_cases").select("*").eq("company_id",companyId).eq("id",caseId).maybeSingle();return error?{data:null,error:mapExecutionError(error)}:data?{data:caseRow(data),error:null}:{data:null,error:{code:"not_found",message:"Hazırlanmış iş bulunamadı.",cause:null}}},
    listEvidence:(companyId:string,caseId:string)=>list("execution_evidence",companyId,evidenceRow,caseId),
    listAssumptions:(companyId:string,caseId:string)=>list("execution_assumptions",companyId,assumptionRow,caseId),
    listMissingInputs:(companyId:string,caseId:string)=>list("execution_missing_inputs",companyId,missingRow,caseId),
    listArtifacts:(companyId:string,caseId:string)=>list("execution_artifacts",companyId,artifactRow,caseId),
    listDecisions:(companyId:string,caseId:string)=>list("execution_decisions",companyId,decisionRow,caseId),
    listFieldEdits:(companyId:string,caseId:string)=>list("execution_field_edits",companyId,editRow,caseId),
    listEvents:(companyId:string,caseId:string)=>list("execution_events",companyId,eventRow,caseId),
    listOutcomes:(companyId:string,caseId:string)=>list("execution_outcomes",companyId,outcomeRow,caseId),
    async getCaseBundle(companyId:string,caseId:string):Promise<ExecutionRepositoryResult<ExecutionCaseBundle>>{const results=await Promise.all([repo.getCase(companyId,caseId),repo.listEvidence(companyId,caseId),repo.listAssumptions(companyId,caseId),repo.listMissingInputs(companyId,caseId),repo.listArtifacts(companyId,caseId),repo.listDecisions(companyId,caseId),repo.listFieldEdits(companyId,caseId),repo.listEvents(companyId,caseId),repo.listOutcomes(companyId,caseId)]);const failure=results.find(result=>result.error);if(failure?.error)return{data:null,error:failure.error};return{data:{case:results[0].data as ExecutionCase,evidence:results[1].data as ExecutionEvidence[],assumptions:results[2].data as ExecutionAssumption[],missingInputs:results[3].data as ExecutionMissingInput[],artifacts:results[4].data as ExecutionArtifact[],decisions:results[5].data as ExecutionDecision[],fieldEdits:results[6].data as ExecutionFieldEdit[],events:results[7].data as ExecutionEvent[],outcomes:results[8].data as ExecutionOutcome[]},error:null}},
    async prepareQuoteCase(companyId:string,input:PrepareQuoteCaseInput):Promise<ExecutionRepositoryResult<{caseId:string;createdNew:boolean}>>{if(!input.partyId||!input.currency||!input.lines.length)return invalid("Firma, para birimi ve en az bir teklif kalemi zorunludur.");if(input.lines.some(line=>!line.description.trim()||!line.unit.trim()||!Number.isFinite(line.quantity)||line.quantity<=0))return invalid("Her kalem için açıklama, pozitif miktar ve birim zorunludur.");const{data,error}=await client.rpc("prepare_quote_execution_case",{target_company_id:companyId,target_party_id:input.partyId,target_contact_id:input.contactId??null,target_opportunity_id:input.opportunityId??null,target_quote_id:input.quoteId??null,target_responsible_user_id:input.responsibleUserId??null,requested_trigger_type:input.triggerType,requested_currency:input.currency,requested_valid_until:input.validUntil??null,requested_payment_terms:input.paymentTerms??null,requested_delivery_terms:input.deliveryTerms??null,requested_expected_delivery_date:input.expectedDeliveryDate??null,requested_customer_notes:input.customerNotes??null,requested_internal_notes:input.internalNotes??null,requested_lines:input.lines.map(line=>({position:line.position,item_code:line.itemCode??null,description:line.description,quantity:line.quantity,unit:line.unit,unit_price:line.unitPrice??null,discount_type:line.discountType??null,discount_value:line.discountValue??0,vat_rate:line.vatRate??20,other_tax_rate:line.otherTaxRate??0})),requested_review_due_at:input.reviewDueAt??null});if(error)return{data:null,error:mapExecutionError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{caseId:String(r.case_id),createdNew:Boolean(r.created_new)},error:null}},
    async refreshQuoteCase(companyId:string,caseId:string){const{data,error}=await client.rpc("refresh_quote_execution_case",{target_company_id:companyId,target_case_id:caseId});if(error)return{data:null,error:mapExecutionError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{caseId:String(r.case_id),createdNew:Boolean(r.created_new)},error:null}},
    async resolveMissingInput(companyId:string,caseId:string,inputKey:string,resolution:unknown){const{data,error}=await client.rpc("resolve_execution_missing_input",{target_company_id:companyId,target_case_id:caseId,target_input_key:inputKey,resolution});return error?{data:null,error:mapExecutionError(error)}:{data:missingRow(data),error:null}},
    async saveReview(companyId:string,caseId:string,content:PreparedQuoteDraft,category:ExecutionEditCategory,reason?:string|null){const{data,error}=await client.rpc("save_quote_execution_review",{target_company_id:companyId,target_case_id:caseId,reviewed_content:content,edit_category:category,edit_reason:reason??null});return error?{data:null,error:mapExecutionError(error)}:{data:artifactRow<PreparedQuoteDraft>(data),error:null}},
    async saveCoverEmail(companyId:string,caseId:string,content:CoverEmailDraft,reason?:string|null){const{data,error}=await client.rpc("save_execution_text_artifact",{target_company_id:companyId,target_case_id:caseId,target_artifact_type:"cover_email_draft",reviewed_content:content,edit_reason:reason??null});return error?{data:null,error:mapExecutionError(error)}:{data:artifactRow<CoverEmailDraft>(data),error:null}},
    async approve(companyId:string,caseId:string,content?:PreparedQuoteDraft,category:ExecutionEditCategory="other",reason?:string|null):Promise<ExecutionRepositoryResult<ExecutionResult>>{const{data,error}=await client.rpc("approve_quote_execution_case",{target_company_id:companyId,target_case_id:caseId,reviewed_content:content??null,edit_category:category,edit_reason:reason??null});if(error)return{data:null,error:mapExecutionError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{caseId:String(r.case_id),quoteId:str(r.quote_id),quoteNumber:str(r.quote_number),executionSucceeded:Boolean(r.execution_succeeded),errorCode:str(r.error_code)},error:null}},
    async retry(companyId:string,caseId:string):Promise<ExecutionRepositoryResult<ExecutionResult>>{const{data,error}=await client.rpc("retry_quote_execution_case",{target_company_id:companyId,target_case_id:caseId});if(error)return{data:null,error:mapExecutionError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{caseId:String(r.case_id),quoteId:str(r.quote_id),quoteNumber:str(r.quote_number),executionSucceeded:Boolean(r.execution_succeeded),errorCode:str(r.error_code)},error:null}},
    async decide(companyId:string,caseId:string,decision:"reject"|"cancel",reasonCode?:string|null,reasonText?:string|null){if(decision==="reject"&&!reasonCode?.trim())return invalid<ExecutionCase>("Ret nedeni kategorisi zorunludur.");const{data,error}=await client.rpc("submit_execution_case_decision",{target_company_id:companyId,target_case_id:caseId,decision_value:decision,reason_code_value:reasonCode??null,reason_text_value:reasonText??null});return error?{data:null,error:mapExecutionError(error)}:{data:caseRow(data),error:null}}
  };return repo;
}
const repository=createAssistedExecutionRepository(supabase as unknown as AssistedExecutionDataClient);
export const listExecutionCases=repository.listCases;export const listPreparedWork=repository.listPreparedWork;export const getExecutionCase=repository.getCase;export const getExecutionCaseBundle=repository.getCaseBundle;export const prepareQuoteCase=repository.prepareQuoteCase;export const refreshQuoteCase=repository.refreshQuoteCase;export const resolveExecutionMissingInput=repository.resolveMissingInput;export const saveQuoteExecutionReview=repository.saveReview;export const saveExecutionCoverEmail=repository.saveCoverEmail;export const approveQuoteExecutionCase=repository.approve;export const retryQuoteExecutionCase=repository.retry;export const decideExecutionCase=repository.decide;
export type QuoteDraftArtifact=ExecutionArtifact<PreparedQuoteDraft>;export type ReviewSummaryArtifact=ExecutionArtifact<InternalReviewSummary>;export type CoverEmailArtifact=ExecutionArtifact<CoverEmailDraft>;
