import {describe,expect,it,vi} from "vitest";
import {createAssistedExecutionRepository,mapExecutionError,type AssistedExecutionDataClient} from "./assistedExecutionRepository";

const response=(data:unknown,error:unknown=null)=>({data,error});
describe("assisted execution repository",()=>{
  it("maps authorization and lifecycle conflicts safely",()=>{expect(mapExecutionError({code:"42501",message:"raw"}).code).toBe("forbidden");expect(mapExecutionError({code:"23514",message:"raw"}).code).toBe("conflict")});
  it("validates preparation before an RPC",async()=>{const rpc=vi.fn();const repo=createAssistedExecutionRepository({rpc,from:vi.fn()} as unknown as AssistedExecutionDataClient);const result=await repo.prepareQuoteCase("company",{partyId:"",currency:"TRY",triggerType:"manual",lines:[]});expect(result.error?.code).toBe("validation");expect(rpc).not.toHaveBeenCalled()});
  it("uses the controlled preparation operation and preserves idempotency result",async()=>{const rpc=vi.fn().mockResolvedValue(response([{case_id:"case",created_new:false}]));const repo=createAssistedExecutionRepository({rpc,from:vi.fn()} as unknown as AssistedExecutionDataClient);const result=await repo.prepareQuoteCase("company",{partyId:"party",currency:"TRY",triggerType:"workbench",lines:[{position:1,description:"Hizmet",quantity:1,unit:"adet"}]});expect(result.data).toEqual({caseId:"case",createdNew:false});expect(rpc).toHaveBeenCalledWith("prepare_quote_execution_case",expect.objectContaining({target_company_id:"company",requested_lines:[expect.objectContaining({unit_price:null})]}))});
  it("requires a rejection category before the decision RPC",async()=>{const rpc=vi.fn();const repo=createAssistedExecutionRepository({rpc,from:vi.fn()} as unknown as AssistedExecutionDataClient);const result=await repo.decide("company","case","reject");expect(result.error?.code).toBe("validation");expect(rpc).not.toHaveBeenCalled()});
  it("does not hide a recorded execution failure",async()=>{const rpc=vi.fn().mockResolvedValue(response([{case_id:"case",quote_id:null,quote_number:null,execution_succeeded:false,error_code:"23514"}]));const repo=createAssistedExecutionRepository({rpc,from:vi.fn()} as unknown as AssistedExecutionDataClient);const result=await repo.approve("company","case");expect(result.data).toMatchObject({executionSucceeded:false,errorCode:"23514",quoteId:null})});
});
