import type { QuoteCurrency } from "../quotes/types";

export type ExecutionCaseStatus = "detected"|"prepared"|"awaiting_review"|"approved"|"executing"|"executed"|"completed"|"rejected"|"expired"|"cancelled"|"failed";
export type EvidenceQuality = "high"|"medium"|"low"|"insufficient";
export type ExecutionArtifactType = "quote_draft"|"internal_review_summary"|"cover_email_draft";
export type ExecutionEditCategory = "commercial_judgment"|"missing_context"|"customer_relationship"|"pricing"|"discount"|"payment_terms"|"delivery"|"wording"|"error_correction"|"other";
export type ExecutionDecisionValue = "approve"|"approve_with_edits"|"reject"|"cancel";

export interface ExecutionCase { id:string; companyId:string; caseType:"quote_preparation"; status:ExecutionCaseStatus; targetPartyId:string; targetContactId:string|null; targetOpportunityId:string|null; targetQuoteId:string|null; executedQuoteId:string|null; responsibleUserId:string; triggerType:"workbench"|"opportunity"|"quotation"|"manual"; triggeredAt:string; preparedAt:string|null; reviewDueAt:string|null; approvedAt:string|null; executedAt:string|null; completedAt:string|null; rulesetKey:"quote-preparation-v1"; rulesetVersion:string; evidenceQuality:EvidenceQuality; summary:string; primaryRecommendation:string; sourceFingerprint:string; replacesCaseId:string|null; createdBy:string; createdAt:string; updatedAt:string; archivedAt:string|null }
export interface ExecutionEvidence { id:string; companyId:string; caseId:string; evidenceType:string; sourceDomain:"crm"|"sales"|"finance"|"customer_health"; sourceType:string; sourceRecordId:string|null; observedAt:string|null; label:string; safeSummary:string; currency:QuoteCurrency|null; amount:number|null; metadata:Record<string,unknown>; createdAt:string }
export interface ExecutionAssumption { id:string; companyId:string; caseId:string; assumptionKey:string; label:string; value:unknown; source:"structured_record"|"company_policy"|"historical_pattern"|"user_input"|"default_policy"; confidence:"high"|"medium"|"low"; requiresConfirmation:boolean; confirmedBy:string|null; confirmedAt:string|null; createdAt:string }
export interface ExecutionMissingInput { id:string; companyId:string; caseId:string; inputKey:string; label:string; severity:"info"|"warning"|"critical"; blocking:boolean; resolutionType:"text"|"number"|"date"|"boolean"|"structured"; resolvedValue:unknown; resolvedBy:string|null; resolvedAt:string|null; createdAt:string }
export interface ExecutionArtifact<T=unknown> { id:string; companyId:string; caseId:string; artifactType:ExecutionArtifactType; versionNumber:number; content:T; sourceFingerprint:string; preparedBy:string; createdAt:string; supersededAt:string|null }
export interface ExecutionDecision { id:string; companyId:string; caseId:string; decision:ExecutionDecisionValue; reasonCode:string|null; reasonText:string|null; decisionSnapshot:Record<string,unknown>; decidedBy:string; decidedAt:string }
export interface ExecutionFieldEdit { id:string; companyId:string; caseId:string; artifactId:string; fieldPath:string; originalValue:unknown; finalValue:unknown; editCategory:ExecutionEditCategory; editedBy:string; editedAt:string }
export interface ExecutionEvent { id:string; companyId:string; caseId:string; eventType:string; actorType:"user"|"system"; actorUserId:string|null; payload:Record<string,unknown>; occurredAt:string }
export interface ExecutionOutcome { id:string; companyId:string; caseId:string; outcomeType:string; sourceDomain:"quotations"|"sales_orders"|"finance"; sourceRecordId:string; observedAt:string; outcomeValue:number|null; currency:QuoteCurrency|null; classification:string|null; conclusive:boolean; notes:string|null; createdAt:string }

export interface PreparedQuoteLine { position:number; item_code:string|null; description:string; quantity:number; unit:string; unit_price:number|null; price_source:Record<string,unknown>|null; discount_type:"percentage"|"fixed"|null; discount_value:number; vat_rate:number; other_tax_rate:number; unit_cost:null }
export interface PreparedQuoteDraft { party_id:string; contact_id:string|null; opportunity_id:string|null; owner_user_id:string; currency:QuoteCurrency; issue_date:string; valid_until:string|null; payment_terms:string|null; delivery_terms:string|null; expected_delivery_date:string|null; customer_notes:string|null; internal_notes:string|null; lines:PreparedQuoteLine[]; warnings:string[] }
export interface InternalReviewSummary { headline:string; evidence:string[]; proposed:{currency:QuoteCurrency;line_count:number}; review_required:string[] }
export interface CoverEmailDraft { subject:string; body:string; template_key:string; send_status:"not_sent" }
export interface ExecutionCaseBundle { case:ExecutionCase; evidence:ExecutionEvidence[]; assumptions:ExecutionAssumption[]; missingInputs:ExecutionMissingInput[]; artifacts:ExecutionArtifact[]; decisions:ExecutionDecision[]; fieldEdits:ExecutionFieldEdit[]; events:ExecutionEvent[]; outcomes:ExecutionOutcome[] }

export interface PrepareQuoteCaseInput { partyId:string; contactId?:string|null; opportunityId?:string|null; quoteId?:string|null; responsibleUserId?:string|null; triggerType:"workbench"|"opportunity"|"quotation"|"manual"; currency:QuoteCurrency; validUntil?:string|null; paymentTerms?:string|null; deliveryTerms?:string|null; expectedDeliveryDate?:string|null; customerNotes?:string|null; internalNotes?:string|null; lines:Array<{position:number;itemCode?:string|null;description:string;quantity:number;unit:string;unitPrice?:number|null;discountType?:"percentage"|"fixed"|null;discountValue?:number;vatRate?:number;otherTaxRate?:number}>; reviewDueAt?:string|null }
export interface ExecutionResult { caseId:string; quoteId:string|null; quoteNumber:string|null; executionSucceeded:boolean; errorCode:string|null }
export type ExecutionRepositoryErrorCode="validation"|"forbidden"|"not_found"|"conflict"|"database";
export interface ExecutionRepositoryError { code:ExecutionRepositoryErrorCode; message:string; cause:unknown }
export type ExecutionRepositoryResult<T>={data:T;error:null}|{data:null;error:ExecutionRepositoryError};
