import { useEffect, useMemo, useState, type ChangeEvent } from 'react'
import { Download, FileSpreadsheet } from 'lucide-react'
import Modal from '../../../surfaces/dashboard/components/Modal'
import { createBusinessContact, createBusinessParty, listBusinessParties } from '../crm/crmRepository'
import type { BusinessContactCreateInput, BusinessParty, BusinessPartyCreateInput } from '../crm/types'
import { Badge, PageState, buttonPrimary, buttonSecondary, inputClass } from '../ui/CRMUI'
import { assignFirm, contactFields, downloadTemplate, fieldLabels, firmFields, importSummary, parseSalesFile, prepareContactRows, prepareFirmRows, recognizeColumns, recognizeImportType, type ColumnMapping, type PreparedImportRow, type RawRow, type SalesImportType, validateFileName } from './salesImport'

interface Props { companyId:string; onClose:()=>void }
type Step='file'|'mapping'|'preview'|'importing'|'result'

export default function SalesImportModal({companyId,onClose}:Props){
  const [step,setStep]=useState<Step>('file'); const [type,setType]=useState<SalesImportType>('firms'); const [headers,setHeaders]=useState<string[]>([]); const [rawRows,setRawRows]=useState<RawRow[]>([]); const [mapping,setMapping]=useState<ColumnMapping>({}); const [rows,setRows]=useState<PreparedImportRow[]>([]); const [parties,setParties]=useState<BusinessParty[]>([]); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{let active=true;void listBusinessParties(companyId,{includeArchived:false}).then(result=>{if(active&&result.data)setParties(result.data)});return()=>{active=false}},[companyId])
  const summary=useMemo(()=>importSummary(rows),[rows])
  const chooseFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setError(null);const invalid=validateFileName(file.name);if(invalid)return setError(invalid);try{const parsed=await parseSalesFile(file);if(!parsed.headers.length||!parsed.rows.length)return setError('Dosyada içe aktarılabilir satır bulunamadı.');const detected=recognizeImportType(parsed.headers);const nextType=detected??type;setType(nextType);setHeaders(parsed.headers);setRawRows(parsed.rows);setMapping(recognizeColumns(parsed.headers,nextType));setStep('mapping')}catch{setError('Dosya okunamadı. Geçerli bir Excel veya CSV dosyası seçin.')}}
  const changeType=(next:SalesImportType)=>{setType(next);if(headers.length)setMapping(recognizeColumns(headers,next))}
  const analyse=()=>{const prepared=type==='firms'?prepareFirmRows(rawRows,mapping,parties):prepareContactRows(rawRows,mapping,parties);setRows(prepared);setStep('preview')}
  const toggle=(index:number)=>setRows(current=>current.map(row=>row.index===index&&row.status==='Hazır'?{...row,selected:!row.selected}:row))
  const selectFirm=(index:number,partyId:string)=>setRows(current=>current.map(row=>row.index===index?assignFirm(row,partyId):row))
  const runImport=async()=>{setStep('importing');const next=[...rows];for(let i=0;i<next.length;i++){const row=next[i];if(!row.selected||row.status!=='Hazır'||!row.input)continue;const result=type==='firms'?await createBusinessParty(companyId,row.input as BusinessPartyCreateInput):await createBusinessContact(companyId,row.input as BusinessContactCreateInput);next[i]={...row,status:result.error?'Aktarılamadı':'İçe aktarıldı',message:result.error?.message??null,selected:false}}setRows(next);setStep('result')}
  const targets=type==='firms'?firmFields:contactFields
  return <Modal title="Excel’den aktar" onClose={onClose} width="960px"><div className="space-y-5">
    <div className="rounded-lg border border-line bg-surface-2 p-4"><p className="text-sm text-ink-soft">Yalnızca Firmalar ve Kişiler desteklenir. Dosyanız onayınızdan önce yerel olarak analiz edilir ve önizlenir.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" className={buttonSecondary} onClick={()=>downloadTemplate('firms')}><Download size={15} className="mr-2 inline"/>Firma içe aktarma şablonu</button><button type="button" className={buttonSecondary} onClick={()=>downloadTemplate('contacts')}><Download size={15} className="mr-2 inline"/>Kişi içe aktarma şablonu</button></div></div>
    {error&&<div role="alert" className="rounded-lg border border-crimson/25 bg-crimson/5 p-3 text-sm text-crimson">{error}</div>}
    {step==='file'&&<div className="space-y-4"><label className="block text-sm font-medium text-ink">İçe aktarma türü<select className={`${inputClass} mt-2`} value={type} onChange={e=>changeType(e.target.value as SalesImportType)}><option value="firms">Firmalar</option><option value="contacts">Kişiler</option></select></label><label className="focus-within:focus-ring flex cursor-pointer flex-col items-center rounded-card border border-dashed border-line px-6 py-10 text-center"><FileSpreadsheet className="text-crimson"/><span className="mt-3 font-medium text-ink">Excel veya CSV dosyası seçin</span><span className="mt-1 text-xs text-ink-mute">.xlsx, .xls veya .csv</span><input className="sr-only" type="file" accept=".xlsx,.xls,.csv" onChange={e=>void chooseFile(e)}/></label></div>}
    {step==='mapping'&&<div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">İçe aktarma türü<select className={`${inputClass} mt-2`} value={type} onChange={e=>changeType(e.target.value as SalesImportType)}><option value="firms">Firmalar</option><option value="contacts">Kişiler</option></select></label><div className="text-sm text-ink-soft">{rawRows.length} satır analiz edildi. Otomatik eşleşmeleri kontrol edin.</div></div><div className="max-h-80 overflow-auto rounded-lg border border-line"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-surface"><tr><th className="p-3">Dosya sütunu</th><th className="p-3">Octo alanı</th></tr></thead><tbody>{headers.map(header=><tr key={header} className="border-t border-line"><td className="p-3 text-ink">{header}</td><td className="p-3"><select aria-label={`${header} sütun eşlemesi`} className={inputClass} value={mapping[header]??''} onChange={e=>setMapping(m=>({...m,[header]:e.target.value}))}><option value="">İçe aktarma</option>{targets.map(field=><option key={field} value={field}>{fieldLabels[field]}</option>)}</select></td></tr>)}</tbody></table></div><div className="flex justify-end gap-3"><button type="button" className={buttonSecondary} onClick={()=>setStep('file')}>Geri</button><button type="button" className={buttonPrimary} onClick={analyse}>Satırları doğrula</button></div></div>}
    {(step==='preview'||step==='result')&&<div className="space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{[['Toplam',summary.total],['Geçerli',summary.valid],['Geçersiz',summary.invalid],['Mükerrer',summary.duplicates],['Eşleşme gerekli',summary.unresolved],['Seçili',summary.selected]].map(([label,value])=><div key={label} className="rounded-lg bg-surface-2 p-3"><div className="text-xs text-ink-mute">{label}</div><div className="mt-1 text-xl font-medium text-ink">{value}</div></div>)}</div>{step==='result'&&<div role="status" className="rounded-lg border border-line p-4 text-sm text-ink-soft"><strong className="text-ink">Sonuç:</strong> {summary.succeeded} satır içe aktarıldı, {summary.failed} satır aktarılamadı. Başarısız satırlar aşağıda ayrı gösterilir.</div>}<div className="max-h-96 overflow-auto rounded-lg border border-line"><table className="w-full min-w-[720px] text-left text-sm"><thead className="sticky top-0 bg-surface"><tr><th className="p-3">Seç</th><th className="p-3">Satır</th><th className="p-3">Durum</th><th className="p-3">Firma / kişi</th><th className="p-3">Vergi kimliği</th><th className="p-3">Açıklama / eşleşme</th></tr></thead><tbody>{rows.map(row=><tr key={row.index} className="border-t border-line"><td className="p-3"><input aria-label={`${row.index+2}. satırı seç`} type="checkbox" checked={row.selected} disabled={row.status!=='Hazır'} onChange={()=>toggle(row.index)}/></td><td className="p-3">{row.index+2}</td><td className="p-3"><Badge muted={row.status!=='Hazır'&&row.status!=='İçe aktarıldı'}>{row.status}</Badge></td><td className="max-w-48 truncate p-3">{row.raw['Kayıt']||'—'}</td><td className="p-3 font-mono text-xs">{row.taxIdMasked}</td><td className="p-3">{row.status==='Eşleşme gerekli'&&type==='contacts'?<select aria-label={`${row.index+2}. satır firma eşleşmesi`} className={inputClass} value="" onChange={e=>selectFirm(row.index,e.target.value)}><option value="">Firma seçin</option>{parties.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select>:row.message||'—'}</td></tr>)}</tbody></table></div><div className="flex justify-end gap-3">{step==='preview'&&<><button type="button" className={buttonSecondary} onClick={()=>setStep('mapping')}>Eşlemeye dön</button><button type="button" className={buttonPrimary} disabled={!summary.selected} onClick={()=>void runImport()}>Seçili satırları içe aktar</button></>}{step==='result'&&<button type="button" className={buttonPrimary} onClick={onClose}>Tamamla</button>}</div></div>}
    {step==='importing'&&<PageState kind="loading" message="Seçili kayıtlar güvenli biçimde içe aktarılıyor…"/>}
  </div></Modal>
}
