import { useCallback, useEffect, useMemo, useState } from 'react'
import { Plus, Search, UserRound } from 'lucide-react'
import { useCompanies } from '../../../company/companyContext'
import Modal from '../../../surfaces/dashboard/components/Modal'
import { archiveBusinessContact, createBusinessContact, listBusinessContacts, listBusinessParties, updateBusinessContact } from '../crm/crmRepository'
import type { BusinessContact, BusinessContactCreateInput, BusinessContactUpdateInput, BusinessParty, ContactDecisionRole } from '../crm/types'
import ContactForm from './ContactForm'
import { Badge, PageState, buttonPrimary, inputClass } from './CRMUI'
import { canWriteCRM, decisionLabels, filterContacts, fullName } from './salesViewModel'

export default function ContactsPage() {
  const { activeCompany } = useCompanies(); const canWrite = canWriteCRM(activeCompany)
  const [contacts, setContacts] = useState<BusinessContact[]>([]); const [parties, setParties] = useState<BusinessParty[]>([]); const [state, setState] = useState<'loading'|'error'|'ready'>('loading')
  const [editing, setEditing] = useState<BusinessContact|null>(null); const [modalOpen, setModalOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string|null>(null); const [notice, setNotice] = useState<string|null>(null)
  const [filters, setFilters] = useState<{ search: string; partyId: string; decisionRole: ''|ContactDecisionRole; primary: ''|'primary'|'other'; includeArchived: boolean }>({ search: '', partyId: '', decisionRole: '', primary: '', includeArchived: false })
  const load = useCallback(async () => { if (!activeCompany) return; const [contactResult, partyResult] = await Promise.all([listBusinessContacts(activeCompany.id, undefined, { includeArchived: true }), listBusinessParties(activeCompany.id, { includeArchived: true })]); if (contactResult.error || partyResult.error) return setState('error'); setContacts(contactResult.data); setParties(partyResult.data); setState('ready') }, [activeCompany])
  // The effect synchronizes this route with the active company's remote CRM records.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const visible = useMemo(() => filterContacts(contacts, parties, filters), [contacts, parties, filters]); const names = useMemo(() => new Map(parties.map(p => [p.id, p.displayName])), [parties])
  const clear = () => setFilters({ search: '', partyId: '', decisionRole: '', primary: '', includeArchived: false })
  const run = async (operation: () => Promise<{ error: { message: string } | null }>, success: string) => { setSaving(true); setError(null); const result = await operation(); setSaving(false); if (result.error) return setError(result.error.message); setModalOpen(false); setEditing(null); setNotice(success); await load() }
  return <main className="mx-auto max-w-7xl space-y-5 px-4 py-6 md:px-8 md:py-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-serif text-2xl text-ink">Kişiler</h2><p className="mt-1 text-sm text-ink-soft">Firmalara bağlı ticari kişileri yönetin.</p></div>{canWrite && <button type="button" className={buttonPrimary} onClick={() => { setEditing(null); setError(null); setModalOpen(true) }}><Plus size={16} className="mr-2 inline"/>Yeni kişi</button>}</div>
    {notice && <div role="status" className="rounded-lg border border-emerald-600/20 bg-emerald-600/10 px-4 py-3 text-sm text-emerald-800">{notice}</div>}
    <section aria-label="Kişi filtreleri" className="grid gap-3 rounded-card border border-line bg-surface p-4 md:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><span className="sr-only">Kişi ara</span><Search size={16} className="absolute left-3 top-3 text-ink-mute"/><input className={`${inputClass} pl-9`} placeholder="Ad, firma, e-posta veya telefon ara" value={filters.search} onChange={e => setFilters(f => ({ ...f, search: e.target.value }))}/></label><label><span className="sr-only">Firma</span><select className={inputClass} value={filters.partyId} onChange={e => setFilters(f => ({ ...f, partyId: e.target.value }))}><option value="">Tüm firmalar</option>{parties.map(p => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label><span className="sr-only">Karar rolü</span><select className={inputClass} value={filters.decisionRole} onChange={e => setFilters(f => ({ ...f, decisionRole: e.target.value as typeof f.decisionRole }))}><option value="">Tüm karar rolleri</option>{Object.entries(decisionLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label><span className="sr-only">Birincil kişi</span><select className={inputClass} value={filters.primary} onChange={e => setFilters(f => ({ ...f, primary: e.target.value as typeof f.primary }))}><option value="">Tüm kişiler</option><option value="primary">Yalnızca birincil</option><option value="other">Birincil olmayanlar</option></select></label><div className="flex flex-wrap items-center gap-3 lg:col-span-5"><label className="flex items-center gap-2 text-sm text-ink-soft"><input type="checkbox" checked={filters.includeArchived} onChange={e => setFilters(f => ({ ...f, includeArchived: e.target.checked }))}/>Arşivdekiler</label><button type="button" onClick={clear} className="text-xs font-medium text-crimson hover:underline">Filtreleri temizle</button></div></section>
    {state === 'loading' && <PageState kind="loading" message="Kişiler yükleniyor…" />}{state === 'error' && <PageState kind="error" message="Kişiler yüklenemedi." retry={() => { setState('loading'); void load() }} />}{state === 'ready' && visible.length === 0 && <PageState kind="empty" message={contacts.length === 0 ? (canWrite ? 'Henüz kişi yok. Önce mevcut bir firmaya kişi ekleyebilirsiniz.' : 'Bu şirkette henüz kişi kaydı bulunmuyor.') : 'Filtrelerle eşleşen kişi bulunamadı.'} />}
    {state === 'ready' && visible.length > 0 && <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(contact => <article key={contact.id} className="min-w-0 rounded-card border border-line bg-surface p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-crimson/10 text-crimson"><UserRound size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-ink">{fullName(contact)}</h3>{contact.isPrimary && <Badge>Birincil</Badge>}{contact.archivedAt && <Badge muted>Arşivde</Badge>}</div><p className="mt-1 text-sm font-medium text-crimson">{names.get(contact.partyId) ?? 'Firma bulunamadı'}</p></div></div><dl className="mt-4 space-y-2 text-sm"><div><dt className="inline text-ink-mute">Görev: </dt><dd className="inline text-ink-soft">{[contact.jobTitle, contact.department].filter(Boolean).join(' · ') || '—'}</dd></div><div><dt className="inline text-ink-mute">Karar rolü: </dt><dd className="inline text-ink-soft">{contact.decisionRole ? decisionLabels[contact.decisionRole] : '—'}</dd></div><div className="truncate text-ink-soft">{contact.email || '—'} · {contact.phone || '—'}</div></dl>{canWrite && !contact.archivedAt && <div className="mt-4 flex gap-3 border-t border-line pt-3"><button type="button" className="text-xs font-medium text-crimson hover:underline" onClick={() => { setEditing(contact); setError(null); setModalOpen(true) }}>Düzenle</button><button type="button" className="text-xs font-medium text-crimson hover:underline" onClick={() => void run(() => archiveBusinessContact(activeCompany!.id, contact.id), 'İlgili kişi arşivlendi.')}>Arşivle</button></div>}</article>)}</div>}
    {modalOpen && <Modal title={editing ? 'İlgili kişiyi düzenle' : 'Yeni ilgili kişi'} onClose={() => !saving && setModalOpen(false)} width="720px"><ContactForm contact={editing ?? undefined} parties={parties} saving={saving} serverError={error} onCancel={() => setModalOpen(false)} onCreate={(input: BusinessContactCreateInput) => void run(() => createBusinessContact(activeCompany!.id, input), 'İlgili kişi oluşturuldu.')} onUpdate={(input: BusinessContactUpdateInput) => void run(() => updateBusinessContact(activeCompany!.id, editing!.id, input), 'İlgili kişi güncellendi.')} /></Modal>}
  </main>
}
