import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Archive, Pencil, Plus } from 'lucide-react'
import { useCompanies } from '../../../company/companyContext'
import Modal from '../../../surfaces/dashboard/components/Modal'
import { archiveBusinessContact, archiveBusinessParty, createBusinessContact, getBusinessParty, listBusinessContacts, setBusinessPartyRoles, updateBusinessContact, updateBusinessParty } from '../crm/crmRepository'
import { BUSINESS_PARTY_ROLES } from '../crm/validation'
import type { BusinessContact, BusinessParty, BusinessPartyRoleName } from '../crm/types'
import ContactForm from './ContactForm'
import FirmForm from './FirmForm'
import { Badge, PageState, buttonPrimary, buttonSecondary } from './CRMUI'
import { canWriteCRM, channelLabels, decisionLabels, formatDate, fullName, roleLabels, statusLabels } from './salesViewModel'
import QuoteLinks from '../quotes/ui/QuoteLinks'
import OrderLinks from '../orders/ui/OrderLinks'
import FirmFinancePanel from '../../finance/ui/FirmFinancePanel'

export default function FirmDetailPage() {
  const { activeCompany } = useCompanies(); const { partyId = '' } = useParams(); const navigate = useNavigate(); const canWrite = canWriteCRM(activeCompany)
  const [party, setParty] = useState<BusinessParty | null>(null); const [contacts, setContacts] = useState<BusinessContact[]>([]); const [state, setState] = useState<'loading'|'error'|'not-found'|'ready'>('loading')
  const [modal, setModal] = useState<null|'edit'|'roles'|'archive'|'contact'>(null); const [editingContact, setEditingContact] = useState<BusinessContact|null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string|null>(null); const [notice, setNotice] = useState<string|null>(null); const [selectedRoles, setSelectedRoles] = useState<BusinessPartyRoleName[]>([])
  const load = useCallback(async () => {
    if (!activeCompany || !partyId) return
    const [partyResult, contactResult] = await Promise.all([getBusinessParty(activeCompany.id, partyId, true), listBusinessContacts(activeCompany.id, partyId)])
    if (partyResult.error?.code === 'not_found') return setState('not-found')
    if (partyResult.error || contactResult.error) return setState('error')
    setParty(partyResult.data); setContacts(contactResult.data); setSelectedRoles(partyResult.data.roles); setState('ready')
  }, [activeCompany, partyId])
  // The effect synchronizes this route with the selected remote CRM record.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const run = async (operation: () => Promise<{ error: { message: string } | null }>, success: string, after?: () => void) => { setSaving(true); setError(null); const result = await operation(); setSaving(false); if (result.error) return setError(result.error.message); setModal(null); setEditingContact(null); setNotice(success); after?.(); await load() }
  if (state === 'loading') return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="loading" message="Firma bilgileri yükleniyor…" /></main>
  if (state === 'error') return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="error" message="Firma bilgileri yüklenemedi." retry={() => { setState('loading'); void load() }} /></main>
  if (state === 'not-found' || !party) return <main className="mx-auto max-w-6xl px-4 py-8 md:px-8"><PageState kind="empty" message="Firma bulunamadı veya bu şirkette görüntülenemiyor." /><Link className={`${buttonSecondary} mt-4 inline-block`} to="/dashboard/satis/firmalar">Firmalara dön</Link></main>
  const values = [['VKN / TCKN', party.taxId], ['Vergi dairesi', party.taxOffice], ['Telefon', party.mainPhone], ['E-posta', party.mainEmail], ['Web sitesi', party.website], ['Sektör', party.sector], ['Şehir / ülke', [party.city, party.countryCode].filter(Boolean).join(' · ')], ['Adres', party.address], ['Kaynak', party.source], ['Notlar', party.notes], ['Oluşturulma', formatDate(party.createdAt)], ['Güncellenme', formatDate(party.updatedAt)]]
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 md:px-8 md:py-8">
    <Link to="/dashboard/satis/firmalar" className="focus-ring inline-flex items-center gap-2 rounded text-sm text-ink-soft hover:text-crimson"><ArrowLeft size={16}/>Firmalara dön</Link>
    {notice && <div role="status" className="rounded-lg border border-emerald-600/20 bg-emerald-600/10 px-4 py-3 text-sm text-emerald-800">{notice}</div>}
    <header className="rounded-card border border-line bg-surface p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="font-serif text-3xl text-ink">{party.displayName}</h1><Badge>{statusLabels[party.relationshipStatus]}</Badge>{party.archivedAt && <Badge muted>Arşivde</Badge>}</div>{party.legalName && party.legalName !== party.displayName && <p className="mt-2 text-sm text-ink-soft">{party.legalName}</p>}<div className="mt-4 flex flex-wrap gap-2">{party.roles.map(role => <Badge key={role}>{roleLabels[role]}</Badge>)}</div></div>{canWrite && !party.archivedAt && <div className="flex flex-wrap gap-2"><button type="button" className={buttonSecondary} onClick={() => { setError(null); setModal('edit') }}><Pencil size={15} className="mr-2 inline"/>Düzenle</button><button type="button" className={buttonSecondary} onClick={() => setModal('archive')}><Archive size={15} className="mr-2 inline"/>Arşivle</button></div>}</div></header>
    <section className="rounded-card border border-line bg-surface p-5 md:p-7"><h2 className="font-serif text-xl text-ink">Genel Bilgiler</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{values.map(([label,value]) => <div key={label}><dt className="text-xs font-medium uppercase tracking-wide text-ink-mute">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm text-ink-soft">{value || '—'}</dd></div>)}</dl></section>
    <section className="rounded-card border border-line bg-surface p-5 md:p-7"><div className="flex items-center justify-between gap-3"><h2 className="font-serif text-xl text-ink">Kişiler</h2>{canWrite && !party.archivedAt && <button type="button" className={buttonPrimary} onClick={() => { setEditingContact(null); setError(null); setModal('contact') }}><Plus size={15} className="mr-2 inline"/>Kişi ekle</button>}</div>{contacts.length === 0 ? <p className="mt-5 text-sm text-ink-soft">Bu firmaya bağlı etkin kişi bulunmuyor.</p> : <div className="mt-5 grid gap-3 md:grid-cols-2">{contacts.map(contact => <article key={contact.id} className="rounded-lg border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-ink">{fullName(contact)}</h3>{contact.isPrimary && <Badge>Birincil</Badge>}</div><p className="mt-1 text-sm text-ink-soft">{[contact.jobTitle, contact.department].filter(Boolean).join(' · ') || 'Unvan belirtilmedi'}</p></div>{canWrite && <div className="flex gap-2"><button type="button" className="text-xs text-crimson hover:underline" onClick={() => { setEditingContact(contact); setError(null); setModal('contact') }}>Düzenle</button><button type="button" className="text-xs text-crimson hover:underline" onClick={() => void run(() => archiveBusinessContact(activeCompany!.id, contact.id), 'İlgili kişi arşivlendi.')}>Arşivle</button></div>}</div><p className="mt-3 text-sm text-ink-soft">{contact.email || '—'} · {contact.phone || '—'}</p><p className="mt-2 text-xs text-ink-mute">{contact.preferredChannel ? channelLabels[contact.preferredChannel] : 'Kanal belirtilmedi'} · {contact.decisionRole ? decisionLabels[contact.decisionRole] : 'Karar rolü belirtilmedi'}</p></article>)}</div>}</section>
    <section className="rounded-card border border-line bg-surface p-5 md:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="font-serif text-xl text-ink">Ticari Roller</h2><div className="mt-3 flex flex-wrap gap-2">{party.roles.map(role => <Badge key={role}>{roleLabels[role]}</Badge>)}</div></div>{canWrite && !party.archivedAt && <button type="button" className={buttonSecondary} onClick={() => { setSelectedRoles(party.roles); setError(null); setModal('roles') }}>Rolleri düzenle</button>}</div></section>
    <QuoteLinks companyId={activeCompany!.id} partyId={party.id} canWrite={canWrite && !party.archivedAt} />
    <OrderLinks companyId={activeCompany!.id} partyId={party.id} />
    <FirmFinancePanel companyId={activeCompany!.id} partyId={party.id} />
    {modal === 'edit' && <Modal title="Firma bilgilerini düzenle" onClose={() => !saving && setModal(null)} width="780px"><FirmForm party={party} saving={saving} serverError={error} onCancel={() => setModal(null)} onUpdate={input => void run(() => updateBusinessParty(activeCompany!.id, party.id, input), 'Firma bilgileri güncellendi.')} /></Modal>}
    {modal === 'roles' && <Modal title="Ticari rolleri düzenle" onClose={() => !saving && setModal(null)}><div className="space-y-5">{error && <div role="alert" className="text-sm text-crimson">{error}</div>}<fieldset><legend className="mb-2 text-sm font-medium">En az bir rol seçin</legend><div className="flex flex-wrap gap-2">{BUSINESS_PARTY_ROLES.map(role => <label key={role} className="flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm"><input type="checkbox" checked={selectedRoles.includes(role)} onChange={() => setSelectedRoles(current => current.includes(role) ? current.filter(item => item !== role) : [...current, role])}/>{roleLabels[role]}</label>)}</div></fieldset><div className="flex justify-end gap-3"><button type="button" className={buttonSecondary} onClick={() => setModal(null)}>Vazgeç</button><button type="button" disabled={saving || selectedRoles.length === 0} className={buttonPrimary} onClick={() => void run(() => setBusinessPartyRoles(activeCompany!.id, party.id, selectedRoles), 'Firma bilgileri güncellendi.')}>Kaydet</button></div></div></Modal>}
    {modal === 'archive' && <Modal title="Firmayı arşivle" onClose={() => !saving && setModal(null)}><p className="text-sm text-ink-soft">Bu firma arşivlenecek. Kayıt ve geçmiş bilgiler korunmaya devam edecek.</p>{error && <p role="alert" className="mt-3 text-sm text-crimson">{error}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" className={buttonSecondary} onClick={() => setModal(null)}>Vazgeç</button><button type="button" disabled={saving} className={buttonPrimary} onClick={() => void run(() => archiveBusinessParty(activeCompany!.id, party.id), 'Firma arşivlendi.', () => navigate('/dashboard/satis/firmalar'))}>Arşivle</button></div></Modal>}
    {modal === 'contact' && <Modal title={editingContact ? 'İlgili kişiyi düzenle' : 'Yeni ilgili kişi'} onClose={() => !saving && setModal(null)} width="720px"><ContactForm contact={editingContact ?? undefined} parties={[party]} fixedPartyId={party.id} saving={saving} serverError={error} onCancel={() => setModal(null)} onCreate={input => void run(() => createBusinessContact(activeCompany!.id, input), 'İlgili kişi oluşturuldu.')} onUpdate={input => void run(() => updateBusinessContact(activeCompany!.id, editingContact!.id, input), 'İlgili kişi güncellendi.')} /></Modal>}
  </main>
}
