import {describe,expect,it} from "vitest";import {createCustomerHealthRepository,mapCustomerHealthError,type CustomerHealthDataClient} from "./customerHealthRepository";import {CUSTOMER_HEALTH_RULESET,validateCompanyRefresh,validateRefreshInput} from "./validation";
class Q implements PromiseLike<{data:unknown;error:unknown|null}>{ops:unknown[][]=[];constructor(private value:unknown=[]){ }select(v:string){this.ops.push(["select",v]);return this}eq(c:string,v:unknown){this.ops.push(["eq",c,v]);return this}gte(c:string,v:unknown){this.ops.push(["gte",c,v]);return this}lte(c:string,v:unknown){this.ops.push(["lte",c,v]);return this}order(c:string,o?:unknown){this.ops.push(["order",c,o]);return this}maybeSingle(){return Promise.resolve({data:Array.isArray(this.value)?this.value[0]??null:this.value,error:null})}then<T1=unknown,T2=never>(ok?:((v:{data:unknown;error:null})=>T1|PromiseLike<T1>)|null,bad?:((r:unknown)=>T2|PromiseLike<T2>)|null){return Promise.resolve({data:this.value,error:null as null}).then(ok,bad)}}
class Client{queries:Array<{table:string;q:Q}>=[];rpcs:Array<{name:string;args:Record<string,unknown>}>=[];rows:Record<string,unknown[]>={customer_health_assessments:[],customer_health_factors:[]};from(table:string){const q=new Q(this.rows[table]??[]);this.queries.push({table,q});return{select:(v:string)=>q.select(v)}}rpc(name:string,args:Record<string,unknown>){this.rpcs.push({name,args});return Promise.resolve({data:name==="refresh_customer_health_assessment"?[{assessment_id:"a",health_status:"watch",data_sufficiency:"partial",confidence:"medium",created_new:true}]:[{evaluated_count:2,created_count:1,unchanged_count:1,failed_count:0,errors:[]}],error:null})}}
describe("customer health repository",()=>{
 it("uses explicit ruleset version",()=>expect(CUSTOMER_HEALTH_RULESET).toBe("customer-health-v1"));
 it("validates party and dates",()=>{expect(validateRefreshInput({partyId:""})).toBeTruthy();expect(validateRefreshInput({partyId:"p",evaluationDate:"15/07/2026"})).toBeTruthy();expect(validateRefreshInput({partyId:"p",evaluationDate:"2026-07-15"})).toBeNull()});
 it("enforces company refresh hard limit",()=>{expect(validateCompanyRefresh({limit:201})).toBeTruthy();expect(validateCompanyRefresh({limit:200})).toBeNull()});
 it("scopes current list to company and current snapshots",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);await r.listCurrentCustomerHealth("company");expect(c.queries[0].q.ops).toContainEqual(["eq","company_id","company"]);expect(c.queries[0].q.ops).toContainEqual(["eq","is_current",true])});
 it("requires explicit historical access",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);await r.listCustomerHealthHistory("company","party");expect(c.queries[0].q.ops).toContainEqual(["eq","party_id","party"])});
 it("scopes factors, evidence and contexts by assessment",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);await r.listCustomerHealthFactors("c","a");await r.listCustomerHealthEvidence("c","a");await r.listCustomerHealthCurrencyContexts("c","a");expect(c.queries.every(x=>x.q.ops.some(op=>op[0]==="eq"&&op[1]==="company_id"&&op[2]==="c"))).toBe(true);expect(c.queries.every(x=>x.q.ops.some(op=>op[0]==="eq"&&op[1]==="assessment_id"&&op[2]==="a"))).toBe(true)});
 it("refreshes one party only through controlled RPC",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);const result=await r.refreshCustomerHealthAssessment("c",{partyId:"p",evaluationDate:"2026-07-15"});expect(result.data).toMatchObject({healthStatus:"watch",createdNew:true});expect(c.rpcs[0]).toEqual({name:"refresh_customer_health_assessment",args:{target_company_id:"c",target_party_id:"p",evaluation_date:"2026-07-15"}})});
 it("refreshes company through bounded controlled RPC",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);const result=await r.refreshCompanyCustomerHealth("c",{limit:100});expect(result.data).toMatchObject({evaluatedCount:2,createdCount:1,unchangedCount:1});expect(c.rpcs[0].name).toBe("refresh_company_customer_health")});
 it("does not call RPC for invalid input",async()=>{const c=new Client(),r=createCustomerHealthRepository(c as unknown as CustomerHealthDataClient);expect((await r.refreshCustomerHealthAssessment("c",{partyId:""})).error?.code).toBe("validation");expect(c.rpcs).toHaveLength(0)});
 it("maps permission, not-found and conflict safely",()=>{expect(mapCustomerHealthError({code:"42501"}).code).toBe("forbidden");expect(mapCustomerHealthError({code:"P0002"}).code).toBe("not_found");expect(mapCustomerHealthError({code:"23505"}).code).toBe("conflict")});
 it("preserves raw errors internally without logging data",()=>{const raw={code:"XX000",message:"internal"};expect(mapCustomerHealthError(raw).cause).toBe(raw)});
 it("contains no source-domain mutation methods",()=>{const r=createCustomerHealthRepository(new Client() as unknown as CustomerHealthDataClient);expect(Object.keys(r).some(x=>/invoice|payment|order|quote|activity/i.test(x))).toBe(false)});
});
