import { supabase } from "../../../lib/supabase";
import type { CustomerHealthAssessment,CustomerHealthCurrencyContext,CustomerHealthEvidence,CustomerHealthFactor,CustomerHealthListFilters,CustomerHealthRepositoryError,CustomerHealthRepositoryResult,CustomerHealthStatus,CustomerHealthSummary,RefreshCompanyCustomerHealthInput,RefreshCompanyCustomerHealthResult,RefreshCustomerHealthInput,RefreshCustomerHealthResult } from "./types";
import { validateCompanyRefresh,validateRefreshInput } from "./validation";
interface Response{data:unknown;error:unknown|null} interface Query extends PromiseLike<Response>{select(v:string):Query;eq(c:string,v:unknown):Query;gte(c:string,v:unknown):Query;lte(c:string,v:unknown):Query;order(c:string,o?:{ascending?:boolean}):Query;maybeSingle():PromiseLike<Response>} interface Table{select(v:string):Query} export interface CustomerHealthDataClient{from(t:string):Table;rpc(n:string,a:Record<string,unknown>):PromiseLike<Response>}
const obj=(v:unknown):Record<string,unknown>=>typeof v==="object"&&v!==null?v as Record<string,unknown>:{};const num=(v:unknown)=>v===null||v===undefined?null:Number(v);const str=(v:unknown)=>v===null||v===undefined?null:String(v);
const assessment=(v:unknown):CustomerHealthAssessment=>{const r=obj(v);return{id:String(r.id),companyId:String(r.company_id),partyId:String(r.party_id),healthStatus:r.health_status as CustomerHealthStatus,dataSufficiency:r.data_sufficiency as CustomerHealthAssessment["dataSufficiency"],confidence:r.confidence as CustomerHealthAssessment["confidence"],summary:String(r.summary),primaryRiskCode:str(r.primary_risk_code),evaluatedOn:String(r.evaluated_on),evaluatedAt:String(r.evaluated_at),windowStart:String(r.window_start),windowEnd:String(r.window_end),rulesetVersion:String(r.ruleset_version),sourceFingerprint:String(r.source_fingerprint),isCurrent:Boolean(r.is_current),supersededAt:str(r.superseded_at),createdBy:String(r.created_by),createdAt:String(r.created_at)}};
const factor=(v:unknown):CustomerHealthFactor=>{const r=obj(v);return{id:String(r.id),companyId:String(r.company_id),partyId:String(r.party_id),assessmentId:String(r.assessment_id),factorCode:r.factor_code as CustomerHealthFactor["factorCode"],sourceDomain:r.source_domain as CustomerHealthFactor["sourceDomain"],direction:r.direction as CustomerHealthFactor["direction"],severity:r.severity as CustomerHealthFactor["severity"],title:String(r.title),explanation:String(r.explanation),recommendation:str(r.recommendation),observedAt:str(r.observed_at),periodStart:str(r.period_start),periodEnd:str(r.period_end),currency:str(r.currency),metricValue:num(r.metric_value),baselineValue:num(r.baseline_value),thresholdValue:num(r.threshold_value),deltaPct:num(r.delta_pct),amount:num(r.amount),evidenceCount:Number(r.evidence_count),createdAt:String(r.created_at)}};
const evidence=(v:unknown):CustomerHealthEvidence=>{const r=obj(v);return{id:String(r.id),companyId:String(r.company_id),partyId:String(r.party_id),assessmentId:String(r.assessment_id),factorId:String(r.factor_id),sourceType:r.source_type as CustomerHealthEvidence["sourceType"],sourceId:String(r.source_id),observedAt:str(r.observed_at),label:String(r.label),amount:num(r.amount),currency:str(r.currency),createdAt:String(r.created_at)}};
const context=(v:unknown):CustomerHealthCurrencyContext=>{const r=obj(v);return{id:String(r.id),companyId:String(r.company_id),partyId:String(r.party_id),assessmentId:String(r.assessment_id),currency:String(r.currency),completedOrderCount12m:Number(r.completed_order_count_12m),completedOrderValue12m:Number(r.completed_order_value_12m),recentOrderCount90d:Number(r.recent_order_count_90d),recentOrderValue90d:Number(r.recent_order_value_90d),previousOrderCount90d:Number(r.previous_order_count_90d),previousOrderValue90d:Number(r.previous_order_value_90d),openReceivable:Number(r.open_receivable),overdueReceivable:Number(r.overdue_receivable),recentQuoteCount180d:Number(r.recent_quote_count_180d),recentQuoteValue180d:Number(r.recent_quote_value_180d),acceptedQuoteCount180d:Number(r.accepted_quote_count_180d),rejectedQuoteCount180d:Number(r.rejected_quote_count_180d),expiredQuoteCount180d:Number(r.expired_quote_count_180d),createdAt:String(r.created_at)}};
export function mapCustomerHealthError(error:unknown):CustomerHealthRepositoryError{const r=obj(error),code=String(r.code??"");if(code==="42501"||code==="PGRST301")return{code:"forbidden",message:"Müşteri Sağlığı işlemi için şirket yetkiniz bulunmuyor.",cause:error};if(code==="PGRST116"||code==="P0002")return{code:"not_found",message:"Müşteri Sağlığı değerlendirmesi bulunamadı.",cause:error};if(code==="23505")return{code:"conflict",message:"Değerlendirme mevcut snapshot ile çelişiyor. Lütfen yenileyin.",cause:error};return{code:"database",message:"Müşteri Sağlığı işlemi tamamlanamadı. Lütfen yeniden deneyin.",cause:error}}
const invalid=<T>(message:string):CustomerHealthRepositoryResult<T>=>({data:null,error:{code:"validation",message,cause:null}});
export function createCustomerHealthRepository(client:CustomerHealthDataClient){async function list<T>(table:string,companyId:string,mapper:(v:unknown)=>T,configure?:(q:Query)=>Query):Promise<CustomerHealthRepositoryResult<T[]>>{let q=client.from(table).select("*").eq("company_id",companyId);if(configure)q=configure(q);const{data,error}=await q;return error?{data:null,error:mapCustomerHealthError(error)}:{data:(Array.isArray(data)?data:[]).map(mapper),error:null}}async function one<T>(table:string,companyId:string,id:string,mapper:(v:unknown)=>T){const{data,error}=await client.from(table).select("*").eq("company_id",companyId).eq("id",id).maybeSingle();return error?{data:null,error:mapCustomerHealthError(error)}:data?{data:mapper(data),error:null}:{data:null,error:{code:"not_found" as const,message:"Müşteri Sağlığı değerlendirmesi bulunamadı.",cause:null}}}
 const repo={
  listCurrentCustomerHealth:(companyId:string,filters:CustomerHealthListFilters={})=>list("customer_health_assessments",companyId,assessment,q=>{let x=q;if(!filters.includeHistorical)x=x.eq("is_current",true);if(filters.status)x=x.eq("health_status",filters.status);if(filters.partyId)x=x.eq("party_id",filters.partyId);if(filters.evaluatedFrom)x=x.gte("evaluated_on",filters.evaluatedFrom);if(filters.evaluatedTo)x=x.lte("evaluated_on",filters.evaluatedTo);return x.order("evaluated_on",{ascending:false})}),
  async getCurrentCustomerHealthForParty(companyId:string,partyId:string):Promise<CustomerHealthRepositoryResult<CustomerHealthAssessment|null>>{const{data,error}=await client.from("customer_health_assessments").select("*").eq("company_id",companyId).eq("party_id",partyId).eq("is_current",true).maybeSingle();return error?{data:null,error:mapCustomerHealthError(error)}:{data:data?assessment(data):null,error:null}},
  getCustomerHealthAssessment:(companyId:string,id:string)=>one("customer_health_assessments",companyId,id,assessment),
  listCustomerHealthHistory:(companyId:string,partyId:string)=>list("customer_health_assessments",companyId,assessment,q=>q.eq("party_id",partyId).order("evaluated_at",{ascending:false})),
  listCustomerHealthFactors:(companyId:string,assessmentId:string)=>list("customer_health_factors",companyId,factor,q=>q.eq("assessment_id",assessmentId).order("created_at",{ascending:true})),
  listCustomerHealthEvidence:(companyId:string,assessmentId:string)=>list("customer_health_evidence",companyId,evidence,q=>q.eq("assessment_id",assessmentId).order("observed_at",{ascending:false})),
  listCustomerHealthCurrencyContexts:(companyId:string,assessmentId:string)=>list("customer_health_currency_contexts",companyId,context,q=>q.eq("assessment_id",assessmentId).order("currency",{ascending:true})),
  async refreshCustomerHealthAssessment(companyId:string,input:RefreshCustomerHealthInput):Promise<CustomerHealthRepositoryResult<RefreshCustomerHealthResult>>{const invalidMessage=validateRefreshInput(input);if(invalidMessage)return invalid(invalidMessage);const{data,error}=await client.rpc("refresh_customer_health_assessment",{target_company_id:companyId,target_party_id:input.partyId,evaluation_date:input.evaluationDate});if(error)return{data:null,error:mapCustomerHealthError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{assessmentId:String(r.assessment_id),healthStatus:r.health_status as CustomerHealthStatus,dataSufficiency:r.data_sufficiency as RefreshCustomerHealthResult["dataSufficiency"],confidence:r.confidence as RefreshCustomerHealthResult["confidence"],createdNew:Boolean(r.created_new)},error:null}},
  async refreshCompanyCustomerHealth(companyId:string,input:RefreshCompanyCustomerHealthInput={}):Promise<CustomerHealthRepositoryResult<RefreshCompanyCustomerHealthResult>>{const invalidMessage=validateCompanyRefresh(input);if(invalidMessage)return invalid(invalidMessage);const{data,error}=await client.rpc("refresh_company_customer_health",{target_company_id:companyId,target_party_ids:input.partyIds,evaluation_date:input.evaluationDate,party_limit:input.limit??100});if(error)return{data:null,error:mapCustomerHealthError(error)};const r=obj(Array.isArray(data)?data[0]:data);return{data:{evaluatedCount:Number(r.evaluated_count),createdCount:Number(r.created_count),unchangedCount:Number(r.unchanged_count),failedCount:Number(r.failed_count),errors:(Array.isArray(r.errors)?r.errors:[]).map(x=>{const e=obj(x);return{partyId:String(e.party_id),code:String(e.code)}})},error:null}},
  async getCustomerHealthCompanySummary(companyId:string):Promise<CustomerHealthRepositoryResult<CustomerHealthSummary>>{const [a,f]=await Promise.all([repo.listCurrentCustomerHealth(companyId),list("customer_health_factors",companyId,factor,q=>q.eq("direction","negative"))]);if(a.error||f.error)return{data:null,error:(a.error??f.error)!};const currentAssessmentIds=new Set(a.data.map(row=>row.id));const currentFactors=f.data.filter(row=>currentAssessmentIds.has(row.assessmentId));const statusDistribution={healthy:0,watch:0,risky:0,critical:0,insufficient_data:0} as Record<CustomerHealthStatus,number>;for(const row of a.data)statusDistribution[row.healthStatus]++;const distribution:CustomerHealthSummary["negativeFactorDistribution"]={};for(const row of currentFactors)distribution[row.factorCode]=(distribution[row.factorCode]??0)+1;const today=new Date().toISOString().slice(0,10);return{data:{healthyCount:statusDistribution.healthy,watchCount:statusDistribution.watch,riskyCount:statusDistribution.risky,criticalCount:statusDistribution.critical,insufficientDataCount:statusDistribution.insufficient_data,assessmentsRequiringRefresh:a.data.filter(x=>x.evaluatedOn<today).length,oldestCurrentAssessmentDate:a.data.map(x=>x.evaluatedOn).sort()[0]??null,statusDistribution,negativeFactorDistribution:distribution},error:null}}
 };return repo}
const repository=createCustomerHealthRepository(supabase as unknown as CustomerHealthDataClient);
export const listCurrentCustomerHealth=repository.listCurrentCustomerHealth;export const getCurrentCustomerHealthForParty=repository.getCurrentCustomerHealthForParty;export const getCustomerHealthAssessment=repository.getCustomerHealthAssessment;export const listCustomerHealthHistory=repository.listCustomerHealthHistory;export const listCustomerHealthFactors=repository.listCustomerHealthFactors;export const listCustomerHealthEvidence=repository.listCustomerHealthEvidence;export const listCustomerHealthCurrencyContexts=repository.listCustomerHealthCurrencyContexts;export const refreshCustomerHealthAssessment=repository.refreshCustomerHealthAssessment;export const refreshCompanyCustomerHealth=repository.refreshCompanyCustomerHealth;export const getCustomerHealthCompanySummary=repository.getCustomerHealthCompanySummary;
